# Capítulo 12 — Organizar columnas en un DataFrame

## Breve repaso

En el trabajo anterior sobre modificación de columnas aprendimos a transformar valores que ya estaban dentro de un `DataFrame`.

Vimos cómo corregir textos con espacios innecesarios, unificar mayúsculas y minúsculas, reemplazar valores específicos con `replace()`, encadenar transformaciones y modificar columnas numéricas. También discutimos cuándo conviene modificar una columna existente y cuándo es mejor crear una nueva versión para conservar los datos originales.

En este capítulo vamos a trabajar con otro tipo de transformación: la organización de columnas.

Hasta ahora nos concentramos principalmente en los valores de las columnas. Ahora vamos a mirar la estructura del `DataFrame`: cómo se llaman sus columnas, cuáles queremos conservar, cuáles podemos eliminar y en qué orden conviene presentarlas.

Estas operaciones son importantes porque un dataset no solo debe contener datos correctos. También debe estar organizado de manera clara. Un `DataFrame` con nombres de columnas confusos, variables innecesarias o columnas desordenadas puede dificultar el análisis, aunque sus valores sean correctos.

A lo largo del capítulo vamos a trabajar con operaciones como renombrar columnas, eliminar columnas, reordenar variables y construir una versión más clara del dataset.

Al finalizar este capítulo deberías poder:

- Revisar los nombres de las columnas de un `DataFrame`.
- Renombrar columnas usando `rename()`.
- Eliminar columnas usando `drop()`.
- Comprender cuándo conviene eliminar una columna y cuándo conservarla.
- Reordenar columnas para mejorar la lectura del dataset.
- Crear una versión organizada del `DataFrame`.
- Verificar la estructura final luego de modificar columnas.
- Reconocer errores frecuentes al organizar columnas.

## Dataset de trabajo

Para trabajar con organización de columnas vamos a usar una nueva versión del dataset de ventas de una tienda escolar.

Esta vez, el problema principal no estará en los valores de las filas, sino en la estructura de la tabla. Algunas columnas tendrán nombres poco claros, abreviaturas, espacios o estilos de escritura diferentes.

Esto es muy frecuente en datasets reales. A veces recibimos archivos donde las columnas fueron nombradas por distintas personas, exportadas desde sistemas externos o armadas rápidamente sin seguir un criterio uniforme.

Nuestro objetivo será transformar esa estructura inicial en un `DataFrame` más claro y cómodo para analizar.

In [27]:
import pandas as pd

datos = {
    "Producto vendido": [
        "Cuaderno", "Lapicera", "Mochila", "Regla", "Cartuchera",
        "Calculadora", "Auriculares", "Resaltadores", "Guardapolvo", "Compas"
    ],
    "Cat": [
        "Libreria", "Libreria", "Accesorios", "Libreria", "Accesorios",
        "Tecnologia", "Tecnologia", "Libreria", "Indumentaria", "Libreria"
    ],
    "Precio Unitario": [
        1200, 350, 8500, 500, 3200,
        18500, 7600, 2100, 14500, 2600
    ],
    "Cant.": [
        15, 40, 5, 25, 8,
        3, 6, 12, 4, 10
    ],
    "Sucursal Venta": [
        "Centro", "Centro", "Norte", "Sur", "Norte",
        "Centro", "Sur", "Centro", "Norte", "Sur"
    ],
    "Pago": [
        "Efectivo", "Debito", "Credito", "Efectivo", "Debito",
        "Credito", "Credito", "Debito", "Credito", "Efectivo"
    ],
    "Fecha venta": [
        "2024-03-01", "2024-03-01", "2024-03-02", "2024-03-02", "2024-03-03",
        "2024-03-03", "2024-03-04", "2024-03-04", "2024-03-05", "2024-03-05"
    ],
    "Código interno": [
        "A001", "A002", "B010", "A003", "B011",
        "T020", "T021", "A004", "I030", "A005"
    ]
}

df = pd.DataFrame(datos)

df

,Producto vendido,Cat,Precio Unitario,Cant.,Sucursal Venta,Pago,Fecha venta,Código interno
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01,A001
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01,A002
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02,B010
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02,A003
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03,B011
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03,T020
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04,T021
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04,A004
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05,I030
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05,A005

Al observar el `DataFrame`, vemos que los datos son comprensibles, pero los nombres de las columnas no siguen un criterio uniforme.

Algunas columnas tienen espacios, como `Producto vendido` o `Precio Unitario`. Otras usan abreviaturas, como `Cat` o `Cant.`. También hay nombres que podrían ser más descriptivos, como `Pago`, que en realidad representa la forma de pago.

Estos detalles pueden parecer menores, pero afectan la claridad del código. Es más cómodo y menos propenso a errores trabajar con nombres de columnas consistentes, descriptivos y fáciles de escribir.


## Qué significa organizar columnas

Organizar columnas significa revisar y ajustar la estructura del `DataFrame` para que sea más clara y fácil de usar.

Esto puede incluir varias tareas. Por ejemplo, podemos renombrar columnas para que tengan nombres más descriptivos, eliminar columnas que no necesitamos, reordenar variables para que la tabla sea más legible o construir una versión final del dataset con las columnas que vamos a usar en el análisis.

En este capítulo no nos vamos a concentrar en corregir los valores dentro de las columnas, sino en la estructura de la tabla.

Por ejemplo, una columna llamada `Cat` puede entenderse si conocemos el contexto, pero no es tan clara como `categoria`. Una columna llamada `Cant.` puede ser breve, pero un nombre como `cantidad_vendida` describe mejor qué representa la variable.

También es importante evitar nombres incómodos para escribir código. Los nombres con espacios, puntos o mayúsculas mezcladas pueden funcionar, pero suelen ser menos prácticos. Por ejemplo:

```python
df["Producto vendido"]
```

funciona correctamente, pero es más cómodo trabajar con:

```python
df["producto"]
```

o con:

```python
df["producto_vendido"]
```

Una buena organización de columnas no cambia los datos en sí mismos, pero mejora la claridad del trabajo. Hace que el código sea más fácil de leer, reduce errores de escritura y ayuda a que otras personas comprendan mejor el dataset.

## Revisar los nombres actuales

Antes de renombrar, eliminar o reordenar columnas, conviene revisar qué nombres tiene actualmente el `DataFrame`.

Para eso podemos usar el atributo `columns`.

In [28]:
df.columns

Index(['Producto vendido', 'Cat', 'Precio Unitario', 'Cant.', 'Sucursal Venta',
       'Pago', 'Fecha venta', 'Código interno'],
      dtype='object')

La salida muestra todos los nombres de columnas del `DataFrame`.

En nuestro caso, vemos nombres como:

```text
Producto vendido
Cat
Precio Unitario
Cant.
Sucursal Venta
Pago
Fecha venta
Código interno
```

Algunos de estos nombres son comprensibles, pero no todos son igualmente claros o cómodos para trabajar. Por ejemplo, `Cat` probablemente significa categoría, pero el nombre completo `categoria` sería más explícito. Algo parecido ocurre con `Cant.`, que podemos interpretar como cantidad, aunque `cantidad_vendida` sería más descriptivo.

También podemos convertir los nombres de columnas en una lista de Python:

In [29]:
list(df.columns)

['Producto vendido',
 'Cat',
 'Precio Unitario',
 'Cant.',
 'Sucursal Venta',
 'Pago',
 'Fecha venta',
 'Código interno']

Esta forma suele ser más cómoda para revisar los nombres, copiarlos o planificar cambios.

Antes de organizar columnas, es útil hacernos algunas preguntas:

```text
¿Los nombres son claros?
¿Hay abreviaturas poco descriptivas?
¿Hay espacios o signos que puedan incomodar al escribir código?
¿Los nombres siguen un mismo estilo?
¿Hay columnas que no vamos a necesitar?
¿Conviene reordenar las columnas para que la tabla se lea mejor?
```

Estas preguntas nos ayudan a tomar decisiones antes de modificar la estructura del `DataFrame`.

## Renombrar columnas con rename()

Una de las formas más claras de cambiar nombres de columnas en Pandas es usar el método `rename()`.

Este método permite indicar qué columnas queremos renombrar y qué nuevo nombre debe recibir cada una.

Para eso usamos un diccionario. En ese diccionario, cada clave es el nombre actual de una columna, y cada valor es el nuevo nombre que queremos asignarle.

In [30]:
df = df.rename(columns={
    "Producto vendido": "producto",
    "Cat": "categoria",
    "Precio Unitario": "precio_unitario",
    "Cant.": "cantidad_vendida",
    "Sucursal Venta": "sucursal",
    "Pago": "forma_pago",
    "Fecha venta": "fecha"
})

df

,producto,categoria,precio_unitario,cantidad_vendida,sucursal,forma_pago,fecha,Código interno
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01,A001
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01,A002
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02,B010
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02,A003
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03,B011
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03,T020
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04,T021
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04,A004
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05,I030
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05,A005

Ahora el `DataFrame` tiene nombres de columnas más claros y consistentes.

Podemos revisar nuevamente los nombres:

In [31]:
df.columns

Index(['producto', 'categoria', 'precio_unitario', 'cantidad_vendida',
       'sucursal', 'forma_pago', 'fecha', 'Código interno'],
      dtype='object')

Los nombres nuevos siguen un criterio común:

```text
producto
categoria
precio_unitario
cantidad_vendida
sucursal
forma_pago
fecha
Código interno
```

La columna `Código interno` todavía conserva su nombre original. Esto ocurrió porque no la incluimos en el diccionario de reemplazos.

Con `rename()`, Pandas solo cambia los nombres de las columnas indicadas. Las columnas que no aparecen en el diccionario quedan como estaban.

Esto puede ser útil cuando queremos modificar solo algunas columnas sin afectar el resto del `DataFrame`.

## Guardar el resultado de rename()

En la celda anterior escribimos:

```python
df = df.rename(columns={
    "Producto vendido": "producto",
    "Cat": "categoria",
    "Precio Unitario": "precio_unitario",
    "Cant.": "cantidad_vendida",
    "Sucursal Venta": "sucursal",
    "Pago": "forma_pago",
    "Fecha venta": "fecha"
})
```

Es importante observar que asignamos el resultado nuevamente a la variable `df`.

Esto significa que reemplazamos el `DataFrame` anterior por una nueva versión con los nombres de columnas modificados.

Si usáramos `rename()` sin guardar el resultado, Pandas mostraría una versión renombrada, pero el `DataFrame` original seguiría igual.

Veamos un ejemplo pequeño para entenderlo mejor.

In [32]:
df_ejemplo = pd.DataFrame({
    "Nombre Producto": ["Cuaderno", "Lapicera"],
    "Precio": [1200, 350]
})

df_ejemplo

  Nombre Producto  Precio
0        Cuaderno    1200
1        Lapicera     350

In [33]:
df_ejemplo.rename(columns={
    "Nombre Producto": "producto",
    "Precio": "precio"
})

   producto  precio
0  Cuaderno    1200
1  Lapicera     350

La salida muestra una versión con nombres modificados. Sin embargo, si volvemos a mostrar `df_ejemplo`, veremos que conserva los nombres originales.

In [34]:
df_ejemplo

  Nombre Producto  Precio
0        Cuaderno    1200
1        Lapicera     350

Para conservar el cambio, debemos guardar el resultado:

In [35]:
df_ejemplo = df_ejemplo.rename(columns={
    "Nombre Producto": "producto",
    "Precio": "precio"
})

df_ejemplo

   producto  precio
0  Cuaderno    1200
1  Lapicera     350

Esta idea aparece muchas veces en Pandas. Muchos métodos devuelven un nuevo resultado, pero no modifican automáticamente el objeto original. Por eso, cuando queremos conservar una transformación, debemos asignarla a una variable.

## Eliminar columnas con drop()

Además de renombrar columnas, a veces necesitamos eliminar columnas que no vamos a utilizar.

En nuestro `DataFrame` hay una columna llamada `Código interno`. Esa columna podría ser útil para un sistema de gestión, pero tal vez no sea necesaria para el análisis que queremos realizar.

Si decidimos quitarla, podemos usar el método `drop()`.

Para eliminar columnas, usamos el parámetro `columns`.

In [36]:
df = df.drop(columns=["Código interno"])

df

,producto,categoria,precio_unitario,cantidad_vendida,sucursal,forma_pago,fecha
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05

Ahora el `DataFrame` ya no contiene la columna `Código interno`.

Al igual que ocurría con `rename()`, usamos una asignación:

```python
df = df.drop(columns=["Código interno"])
```

Esto significa que guardamos en `df` una nueva versión del `DataFrame`, pero sin esa columna.

Eliminar columnas puede ser útil cuando una variable no aporta información para el análisis, cuando contiene datos redundantes o cuando queremos construir una versión más simple del dataset. Sin embargo, conviene ser cuidadosos. Una columna que parece innecesaria al comienzo puede servir más adelante para verificar información, cruzar datos o reconstruir decisiones.

Por eso, antes de eliminar una columna conviene preguntarnos:

```text
¿Esta columna aporta información útil para el análisis?
¿La información aparece repetida en otra columna?
¿Podría necesitarla más adelante para verificar o cruzar datos?
¿Estoy trabajando sobre una copia o sobre el único DataFrame disponible?
```

En general, si no estamos seguros, puede ser mejor conservar la columna o crear una versión organizada del `DataFrame` en una nueva variable.

## Eliminar más de una columna

`drop()` también permite eliminar varias columnas al mismo tiempo.

Para hacerlo, pasamos una lista con los nombres de las columnas que queremos quitar.

Veamos un ejemplo con un `DataFrame` auxiliar. Vamos a recrear una versión pequeña del dataset para mostrar la eliminación de varias columnas sin afectar el `DataFrame` principal que ya venimos organizando.

In [37]:
df_auxiliar = pd.DataFrame(datos)

df_auxiliar.head()

,Producto vendido,Cat,Precio Unitario,Cant.,Sucursal Venta,Pago,Fecha venta,Código interno
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01,A001
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01,A002
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02,B010
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02,A003
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03,B011

En este `DataFrame` auxiliar todavía aparecen los nombres originales de las columnas.

Supongamos que queremos eliminar las columnas `Código interno` y `Fecha venta`.

In [38]:
df_auxiliar = df_auxiliar.drop(columns=["Código interno", "Fecha venta"])

df_auxiliar.head()

,Producto vendido,Cat,Precio Unitario,Cant.,Sucursal Venta,Pago
0,Cuaderno,Libreria,1200,15,Centro,Efectivo
1,Lapicera,Libreria,350,40,Centro,Debito
2,Mochila,Accesorios,8500,5,Norte,Credito
3,Regla,Libreria,500,25,Sur,Efectivo
4,Cartuchera,Accesorios,3200,8,Norte,Debito

Ahora `df_auxiliar` ya no contiene esas dos columnas.

La estructura general es:

```python
df.drop(columns=["columna_1", "columna_2"])
```

Eliminar varias columnas puede ser útil cuando queremos simplificar un dataset y quedarnos solamente con las variables necesarias. Sin embargo, conviene hacerlo con cuidado. Si eliminamos columnas demasiado pronto, podríamos perder información que luego necesitábamos para revisar el origen de los datos, controlar errores o enriquecer el análisis.

Por eso, muchas veces es preferible trabajar con una copia o con una nueva variable, especialmente durante las primeras etapas de exploración y preparación.

## Reordenar columnas

Además de renombrar o eliminar columnas, también podemos cambiar el orden en que aparecen dentro del `DataFrame`.

Reordenar columnas no modifica los valores. Solo cambia la forma en que se presenta la tabla.

Esto puede ser útil cuando queremos que las variables sigan un orden más lógico. Por ejemplo, podríamos preferir que primero aparezcan las columnas que identifican la venta, luego las variables numéricas y finalmente la información contextual.

En nuestro `DataFrame` actual tenemos estas columnas:

In [39]:
df.columns

Index(['producto', 'categoria', 'precio_unitario', 'cantidad_vendida',
       'sucursal', 'forma_pago', 'fecha'],
      dtype='object')

Podemos crear una lista con el orden deseado:

In [40]:
columnas_ordenadas = [
    "producto",
    "categoria",
    "precio_unitario",
    "cantidad_vendida",
    "sucursal",
    "forma_pago",
    "fecha"
]

Luego usamos esa lista para reorganizar el `DataFrame`:

In [41]:
df = df[columnas_ordenadas]

df

,producto,categoria,precio_unitario,cantidad_vendida,sucursal,forma_pago,fecha
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05

Ahora las columnas aparecen en el orden que indicamos en la lista.

Esta técnica es muy útil porque nos permite construir una versión final del dataset con una estructura más clara.

La idea general es:

```python
df = df[lista_de_columnas_en_el_orden_deseado]
```

Es importante que todos los nombres de la lista existan en el `DataFrame`. Si escribimos mal un nombre de columna o incluimos una columna que no existe, Pandas mostrará un error.

## Construir una versión organizada del DataFrame

Hasta ahora aplicamos varias operaciones por separado: renombramos columnas, eliminamos una columna que no necesitábamos y reordenamos las variables.

En un trabajo real, muchas veces queremos construir una versión organizada del dataset para usarla en el análisis posterior. Esa versión puede conservar solamente las columnas necesarias, con nombres claros y en un orden lógico.

Una forma de hacerlo es crear una nueva variable, por ejemplo `df_organizado`.

Para mostrar el proceso completo, vamos a recrear el `DataFrame` original y aplicar las transformaciones principales.

In [42]:
df_original = pd.DataFrame(datos)

df_organizado = df_original.rename(columns={
    "Producto vendido": "producto",
    "Cat": "categoria",
    "Precio Unitario": "precio_unitario",
    "Cant.": "cantidad_vendida",
    "Sucursal Venta": "sucursal",
    "Pago": "forma_pago",
    "Fecha venta": "fecha"
})

df_organizado = df_organizado.drop(columns=["Código interno"])

df_organizado = df_organizado[
    [
        "producto",
        "categoria",
        "precio_unitario",
        "cantidad_vendida",
        "sucursal",
        "forma_pago",
        "fecha"
    ]
]

df_organizado

,producto,categoria,precio_unitario,cantidad_vendida,sucursal,forma_pago,fecha
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05

En este bloque realizamos tres pasos.

Primero renombramos las columnas para que tengan nombres más claros y consistentes. Luego eliminamos la columna `Código interno`, porque decidimos que no era necesaria para este análisis. Finalmente reordenamos las columnas para que la tabla quede presentada de una manera más cómoda.

El `DataFrame` original sigue estando disponible en la variable `df_original`, mientras que la versión organizada quedó guardada en `df_organizado`.

Esta forma de trabajo es recomendable porque conserva una versión inicial de los datos y, al mismo tiempo, nos permite construir una versión más limpia y clara para continuar el análisis.

## Verificar la estructura final

Después de organizar las columnas, conviene revisar cómo quedó el `DataFrame`.

Podemos empezar consultando sus nombres de columnas:

In [43]:
df_organizado.columns

Index(['producto', 'categoria', 'precio_unitario', 'cantidad_vendida',
       'sucursal', 'forma_pago', 'fecha'],
      dtype='object')

También podemos revisar sus dimensiones:

In [44]:
df_organizado.shape

(10, 7)

Y podemos observar las primeras filas:

In [45]:
df_organizado.head()

,producto,categoria,precio_unitario,cantidad_vendida,sucursal,forma_pago,fecha
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03

Estas verificaciones nos permiten confirmar que la organización se aplicó correctamente.

El `DataFrame` organizado debería tener nombres de columnas claros, no debería incluir columnas que decidimos eliminar y debería presentar las variables en un orden lógico.

También podemos comparar las columnas originales con las columnas organizadas:

In [46]:
print("Columnas originales:")
print(list(df_original.columns))

print()

print("Columnas organizadas:")
print(list(df_organizado.columns))

Columnas originales:
['Producto vendido', 'Cat', 'Precio Unitario', 'Cant.', 'Sucursal Venta', 'Pago', 'Fecha venta', 'Código interno']

Columnas organizadas:
['producto', 'categoria', 'precio_unitario', 'cantidad_vendida', 'sucursal', 'forma_pago', 'fecha']

Esta comparación muestra con claridad qué cambió.

El dataset original conservaba nombres como `Producto vendido`, `Cat`, `Precio Unitario`, `Cant.`, `Sucursal Venta`, `Pago`, `Fecha venta` y `Código interno`.

La versión organizada, en cambio, tiene nombres más consistentes y ya no incluye la columna que decidimos quitar.

Verificar la estructura final es una buena práctica. Cada vez que renombramos, eliminamos o reordenamos columnas, conviene revisar que el resultado coincida con lo que esperábamos.

## Errores frecuentes al organizar columnas

Al organizar columnas en Pandas pueden aparecer algunos errores comunes.

Uno de los más frecuentes es escribir mal el nombre de una columna. Esto puede ocurrir al renombrar, eliminar o reordenar.

Por ejemplo, si intentamos eliminar una columna llamada `"Codigo interno"` sin tilde, pero en el `DataFrame` la columna se llama `"Código interno"` con tilde, Pandas no encontrará esa columna.

In [47]:
# Esta instrucción produciría un error porque la columna se llama "Código interno".
# df_original.drop(columns=["Codigo interno"])

Para evitar este tipo de problemas, conviene revisar los nombres exactos con:

In [48]:
df_original.columns

Index(['Producto vendido', 'Cat', 'Precio Unitario', 'Cant.', 'Sucursal Venta',
       'Pago', 'Fecha venta', 'Código interno'],
      dtype='object')

Otro error frecuente es olvidar guardar el resultado de una operación. Métodos como `rename()` y `drop()` devuelven una nueva versión del `DataFrame`, pero no modifican automáticamente el objeto original si no guardamos el resultado.

Por ejemplo:

In [49]:
df_ejemplo = pd.DataFrame({
    "Producto vendido": ["Cuaderno", "Lapicera"],
    "Precio Unitario": [1200, 350]
})

df_ejemplo.rename(columns={
    "Producto vendido": "producto",
    "Precio Unitario": "precio_unitario"
})

   producto  precio_unitario
0  Cuaderno             1200
1  Lapicera              350

La salida parece mostrar columnas renombradas, pero si volvemos a revisar `df_ejemplo`, veremos que conserva los nombres originales:

In [50]:
df_ejemplo

  Producto vendido  Precio Unitario
0         Cuaderno             1200
1         Lapicera              350

Para conservar el cambio, debemos guardar el resultado:

In [51]:
df_ejemplo = df_ejemplo.rename(columns={
    "Producto vendido": "producto",
    "Precio Unitario": "precio_unitario"
})

df_ejemplo

   producto  precio_unitario
0  Cuaderno             1200
1  Lapicera              350

También puede aparecer un error al reordenar columnas si la lista contiene un nombre que no existe o si olvidamos incluir una columna que queríamos conservar.

In [52]:
# Esta instrucción produciría un error porque "precio" no existe en df_organizado.
# La columna se llama "precio_unitario".

# df_organizado[["producto", "categoria", "precio"]]

Finalmente, debemos tener cuidado al eliminar columnas demasiado pronto. Eliminar una columna puede simplificar el dataset, pero también puede hacernos perder información útil para controles posteriores.

Una buena rutina para organizar columnas podría ser:

```text
revisar nombres actuales
renombrar columnas necesarias
decidir qué columnas conservar o eliminar
reordenar variables
verificar la estructura final
```

Organizar columnas no es solo una cuestión estética. Una estructura clara ayuda a escribir código más legible, reduce errores y facilita el análisis posterior.

## Resumen del capítulo

En este capítulo aprendimos a organizar las columnas de un `DataFrame`.

Hasta ahora habíamos trabajado principalmente con valores: crear columnas nuevas, modificar valores existentes, corregir textos o transformar datos numéricos. En este capítulo, en cambio, nos concentramos en la estructura de la tabla.

Comenzamos con un dataset que tenía nombres de columnas poco uniformes. Algunas columnas tenían espacios, otras usaban abreviaturas y otras tenían nombres que podían ser más claros. Vimos que esos detalles pueden dificultar la escritura del código y hacer menos comprensible el análisis.

Primero revisamos los nombres actuales usando:

```python
df.columns
```

y también convertimos esos nombres en una lista para leerlos con mayor comodidad:

```python
list(df.columns)
```

Después usamos `rename()` para cambiar nombres de columnas. Para eso construimos un diccionario donde cada clave era el nombre original de la columna y cada valor era el nuevo nombre:

```python
df = df.rename(columns={
    "Producto vendido": "producto",
    "Cat": "categoria",
    "Precio Unitario": "precio_unitario",
    "Cant.": "cantidad_vendida",
    "Sucursal Venta": "sucursal",
    "Pago": "forma_pago",
    "Fecha venta": "fecha"
})
```

También vimos que muchos métodos de Pandas no modifican automáticamente el `DataFrame` original. Por eso, si queremos conservar el resultado de una transformación, debemos asignarlo a una variable.

Luego aprendimos a eliminar columnas usando `drop()`:

```python
df = df.drop(columns=["Código interno"])
```

Esta operación puede ser útil cuando una columna no aporta información al análisis, pero también requiere cuidado. Eliminar columnas demasiado pronto puede hacernos perder datos útiles para revisar, verificar o cruzar información más adelante.

Después trabajamos con el reordenamiento de columnas. Para eso creamos una lista con el orden deseado y la usamos para reorganizar el `DataFrame`:

```python
columnas_ordenadas = [
    "producto",
    "categoria",
    "precio_unitario",
    "cantidad_vendida",
    "sucursal",
    "forma_pago",
    "fecha"
]

df = df[columnas_ordenadas]
```

Más adelante integramos estas operaciones en una versión organizada del dataset. Creamos un `DataFrame` original y luego construimos una nueva variable llamada `df_organizado`, con columnas renombradas, una columna eliminada y un orden más claro.

Finalmente, verificamos la estructura final revisando los nombres de columnas, las dimensiones, las primeras filas y comparando las columnas originales con las columnas organizadas.

La idea principal de este capítulo fue:

```text
Organizar columnas permite construir un DataFrame más claro, legible y cómodo para analizar.
```

Una buena estructura de columnas no cambia los datos por sí misma, pero mejora el trabajo posterior. Nombres claros, columnas necesarias y un orden lógico ayudan a escribir código más comprensible y reducen errores.

## Próximo paso

Ya sabemos seleccionar, filtrar, ordenar, crear columnas, modificar valores y organizar la estructura de un `DataFrame`.

El siguiente paso será comenzar a trabajar con valores faltantes. En los datasets reales es muy común encontrar celdas vacías, datos incompletos o valores que Pandas representa como `NaN`.

Aprender a detectar y tratar valores faltantes será una parte central de la limpieza de datos, porque esos valores pueden afectar conteos, promedios, filtros, gráficos y conclusiones.