<a href="https://colab.research.google.com/github/VintaBytes/Ciencia-de-datos/blob/main/CienciaDeDatosConPython/CuadernosColab/CienciaDeDatos_Cap%C3%ADtulo008_Ordenar_datos_en_un_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Abrir en Colab"/></a>

# Capítulo 8 — Ordenar datos en un DataFrame

## Breve repaso

En el trabajo anterior sobre filtros aprendimos a seleccionar filas usando condiciones. Primero construimos filtros simples, como seleccionar ventas de una categoría determinada o ventas con precio mayor que cierto valor. Después avanzamos hacia filtros combinados, usando operadores lógicos como `&`, `|` y `~`.

Eso nos permitió construir selecciones más precisas. Por ejemplo, pudimos pedir ventas de una categoría específica con precio alto, ventas de ciertas sucursales o registros que no pertenecieran a determinado grupo.

En este capítulo vamos a trabajar con otra operación fundamental: ordenar datos.

Ordenar un `DataFrame` significa reorganizar sus filas según los valores de una o más columnas. Esto permite leer mejor la información, encontrar rápidamente valores altos o bajos, comparar registros y construir primeros rankings.

Por ejemplo, podríamos ordenar las ventas por precio, por cantidad vendida, por categoría, por sucursal o por forma de pago. También podríamos combinar filtros y ordenamiento: primero seleccionar las ventas de una categoría y después ordenarlas de mayor a menor precio.

Al finalizar este capítulo deberías poder:

- Ordenar un `DataFrame` usando una columna.
- Ordenar datos en forma ascendente o descendente.
- Ordenar columnas numéricas y columnas de texto.
- Ordenar por más de una columna.
- Combinar filtros con ordenamiento.
- Seleccionar columnas después de ordenar.
- Guardar un resultado ordenado en una nueva variable.
- Reconocer que `sort_values()` no modifica el `DataFrame` original salvo que se indique explícitamente.
- Usar `sort_index()` para ordenar según el índice.

## Dataset de trabajo

Para estudiar cómo ordenar datos vamos a seguir trabajando con el dataset de ventas de una tienda escolar.

Recordemos: cada fila representa una venta registrada. Las columnas indican el producto vendido, la categoría, el precio unitario, la cantidad vendida, la sucursal, la forma de pago y la fecha. Es útil, porqué tiene suficiente variedad para ordenar la información de distintas maneras: por precio, por cantidad vendida, por producto, por categoría, por sucursal o por forma de pago.

In [1]:
import pandas as pd

datos = {
    "producto": [
        "Cuaderno", "Lapicera", "Mochila", "Regla", "Cartuchera",
        "Calculadora", "Auriculares", "Resaltadores", "Guardapolvo", "Compas",
        "Pendrive", "Carpeta", "Goma", "Lapiz", "Agenda"
    ],
    "categoria": [
        "Libreria", "Libreria", "Accesorios", "Libreria", "Accesorios",
        "Tecnologia", "Tecnologia", "Libreria", "Indumentaria", "Libreria",
        "Tecnologia", "Libreria", "Libreria", "Libreria", "Libreria"
    ],
    "precio": [
        1200, 350, 8500, 500, 3200,
        18500, 7600, 2100, 14500, 2600,
        9800, 950, 300, 250, 4300
    ],
    "cantidad_vendida": [
        15, 40, 5, 25, 8,
        3, 6, 12, 4, 10,
        7, 18, 30, 50, 9
    ],
    "sucursal": [
        "Centro", "Centro", "Norte", "Sur", "Norte",
        "Centro", "Sur", "Centro", "Norte", "Sur",
        "Centro", "Norte", "Sur", "Centro", "Sur"
    ],
    "forma_pago": [
        "Efectivo", "Debito", "Credito", "Efectivo", "Debito",
        "Credito", "Credito", "Debito", "Credito", "Efectivo",
        "Debito", "Efectivo", "Efectivo", "Debito", "Credito"
    ],
    "fecha": [
        "2024-03-01", "2024-03-01", "2024-03-02", "2024-03-02", "2024-03-03",
        "2024-03-03", "2024-03-04", "2024-03-04", "2024-03-05", "2024-03-05",
        "2024-03-06", "2024-03-06", "2024-03-07", "2024-03-07", "2024-03-08"
    ]
}

df = pd.DataFrame(datos)

df

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08

Antes de ordenar, conviene observar nuevamente la estructura general del `DataFrame`. Tenemos productos de distintas categorías, precios variados, cantidades vendidas diferentes y registros asociados a distintas sucursales y formas de pago.

Ese tipo de variedad permite que el ordenamiento sea útil. Si todos los precios o todas las cantidades fueran iguales, ordenar no aportaría demasiada información. En cambio, cuando los valores cambian de una fila a otra, ordenar ayuda a detectar rápidamente cuáles son los registros más altos, más bajos o más relevantes para una pregunta de análisis.

## Por qué ordenar datos

Ordenar datos significa reorganizar las filas de un `DataFrame` según los valores de una o más columnas.

Cuando miramos una tabla pequeña, tal vez podamos encontrar ciertos valores a simple vista. Pero a medida que el dataset crece, se vuelve mucho más difícil detectar cuáles son los precios más altos, cuáles son las cantidades más bajas, qué productos aparecen primero alfabéticamente o cómo se distribuyen los registros dentro de una categoría.

El ordenamiento nos ayuda a leer mejor la información. Por ejemplo, si ordenamos las ventas por `precio`, podemos identificar rápidamente los productos más baratos o más caros. Si ordenamos por `cantidad_vendida`, podemos ver qué productos tuvieron mayor o menor cantidad de unidades vendidas. Si ordenamos por `categoria`, podemos agrupar visualmente productos similares.

Ordenar no cambia el significado de los datos. Las filas siguen representando las mismas ventas, pero aparecen en otro orden. Esa reorganización puede facilitar mucho la interpretación.

En Pandas, la herramienta principal para ordenar filas según los valores de una columna es `sort_values()`.

## Ordenar por una columna

Para ordenar un `DataFrame` según los valores de una columna, usamos el método `sort_values()`.

Dentro de los paréntesis indicamos el nombre de la columna que queremos usar como criterio de ordenamiento.

Por ejemplo, si queremos ordenar las ventas según el precio, podemos escribir:

In [2]:
df.sort_values("precio")

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03

El resultado muestra el `DataFrame` ordenado por la columna `precio`.

Por defecto, Pandas ordena de menor a mayor. Por eso, al ordenar por `precio`, las primeras filas corresponden a los productos más baratos y las últimas a los productos más caros.

Esta instrucción no elimina filas ni columnas. Tampoco cambia los valores del dataset. Solamente reorganiza el orden en que aparecen las filas.

Es importante observar que el índice original se conserva. Aunque las filas aparezcan en otro orden, cada una mantiene el índice que tenía en el `DataFrame` original. Esto nos recuerda que ordenar modifica la forma en que vemos la tabla, pero no reinventa los registros.

## Orden ascendente y descendente

Cuando usamos `sort_values()`, Pandas ordena de manera ascendente por defecto.

En una columna numérica, ordenar de forma ascendente significa ir de menor a mayor. Por eso, cuando escribimos:

In [3]:
df.sort_values("precio")

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03

los productos aparecen ordenados desde el precio más bajo hasta el precio más alto.

Si queremos ordenar en sentido contrario, usamos el parámetro `ascending=False`.

In [4]:
df.sort_values("precio", ascending=False)

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07

Ahora el `DataFrame` aparece ordenado de mayor a menor precio. Las primeras filas corresponden a los productos más caros y las últimas a los productos más baratos.

El parámetro `ascending` controla el sentido del ordenamiento:

```text
ascending=True   → orden ascendente
ascending=False  → orden descendente
```

Como `ascending=True` es el valor por defecto, normalmente no hace falta escribirlo si queremos ordenar de menor a mayor. En cambio, sí debemos indicar `ascending=False` cuando queremos ordenar de mayor a menor.

Este detalle es muy útil cuando buscamos valores altos. Por ejemplo, si queremos ver rápidamente los productos más caros, conviene ordenar por precio en forma descendente.

## Ordenar por cantidad vendida

También podemos ordenar el `DataFrame` usando la columna `cantidad_vendida`.

Esto nos permite observar qué productos tuvieron menor o mayor cantidad de unidades vendidas.

Por ejemplo, podemos ordenar las ventas desde la menor cantidad vendida hasta la mayor:

In [5]:
df.sort_values("cantidad_vendida")

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07

En este caso, las primeras filas corresponden a los registros con menos unidades vendidas.

Si queremos ver primero los productos con mayor cantidad vendida, usamos `ascending=False`:

In [6]:
df.sort_values("cantidad_vendida", ascending=False)

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03

Ahora las primeras filas muestran las ventas con mayor cantidad de unidades.

Ordenar por cantidad vendida puede ayudarnos a detectar rápidamente qué productos se vendieron más y cuáles tuvieron menos movimiento. Sin embargo, todavía debemos interpretar estos resultados con cuidado: una cantidad vendida alta no siempre significa mayor ingreso total, porque también depende del precio de cada producto.

Por ejemplo, un producto barato puede vender muchas unidades, mientras que un producto caro puede vender pocas unidades y aun así representar un ingreso importante. Más adelante podremos crear nuevas columnas, como el importe total de cada venta, para analizar mejor ese tipo de situaciones.

## Ordenar columnas de texto

`sort_values()` también puede usarse con columnas de texto.

Cuando ordenamos una columna de texto, Pandas organiza los valores alfabéticamente. Por ejemplo, podemos ordenar el dataset según el nombre del producto.

In [7]:
df.sort_values("producto")

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04

El resultado muestra las filas ordenadas alfabéticamente por la columna `producto`.

También podemos ordenar por `categoria`:

In [8]:
df.sort_values("categoria")

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06

En este caso, los registros quedan agrupados visualmente por categoría. Primero aparecen las filas de una categoría, luego las de otra, y así sucesivamente, siguiendo el orden alfabético.

Ordenar columnas de texto puede ser útil para revisar datos categóricos, detectar valores escritos de manera diferente o simplemente presentar una tabla de forma más clara. Por ejemplo, si una columna de categorías tuviera valores como `"Libreria"`, `"libreria"` y `"Librería"`, al ordenar podríamos notar más fácilmente que existen variantes de escritura que tal vez deberían limpiarse más adelante.

También podemos ordenar textos de manera descendente:

In [9]:
df.sort_values("producto", ascending=False)

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08

En este caso, el orden alfabético se invierte.

Aunque muchas veces usamos `sort_values()` con columnas numéricas, también es una herramienta útil para explorar columnas categóricas o textuales.

## Ordenar por más de una columna

A veces una sola columna no alcanza para organizar bien la información.

Por ejemplo, si ordenamos solamente por `categoria`, los productos quedan agrupados por categoría, pero dentro de cada categoría pueden aparecer en cualquier orden. Tal vez queremos que, dentro de cada categoría, los productos aparezcan ordenados por precio.

Para eso podemos ordenar usando más de una columna.

En `sort_values()`, en lugar de pasar un solo nombre de columna, pasamos una lista de columnas.

In [10]:
df.sort_values(["categoria", "precio"])

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03

Esta instrucción ordena primero por `categoria` y, dentro de cada categoría, ordena por `precio`.

Podemos leerlo así: *agrupá visualmente los registros por categoría y, dentro de cada grupo, mostrá los productos desde el precio más bajo hasta el precio más alto*.

También podemos ordenar por `sucursal` y luego por `cantidad_vendida`:

In [11]:
df.sort_values(["sucursal", "cantidad_vendida"])

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07

En este caso, las filas se ordenan primero por `sucursal`. Luego, dentro de cada sucursal, se ordenan por `cantidad_vendida`.

Ordenar por más de una columna es útil cuando queremos organizar la información con distintos niveles de criterio. Primero definimos el criterio principal y después el criterio secundario.

## Ordenar varias columnas con distintos criterios

Cuando ordenamos por más de una columna, también podemos indicar si cada una debe ordenarse de forma ascendente o descendente.

Para eso usamos el parámetro `ascending`, pero en lugar de pasar un solo valor, pasamos una lista de valores.

Por ejemplo, podemos ordenar por `categoria` de manera ascendente y, dentro de cada categoría, ordenar por `precio` de manera descendente.

In [12]:
df.sort_values(
    ["categoria", "precio"],
    ascending=[True, False]
)

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04

En esta instrucción, la primera columna de ordenamiento es `categoria`, y se ordena alfabéticamente porque indicamos `True`. La segunda columna es `precio`, y se ordena de mayor a menor dentro de cada categoría porque indicamos `False`.

Esto permite construir ordenamientos más expresivos. Por ejemplo, si queremos revisar las ventas por sucursal y, dentro de cada sucursal, ver primero las mayores cantidades vendidas, podemos escribir:

In [13]:
df.sort_values(
    ["sucursal", "cantidad_vendida"],
    ascending=[True, False]
)

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04

En este caso, Pandas ordena primero por `sucursal` y luego, dentro de cada sucursal, muestra las ventas con mayor cantidad vendida al principio.

Cuando usamos varias columnas para ordenar, el orden de las listas importa. La primera columna es el criterio principal, la segunda columna es el criterio secundario, y así sucesivamente.

También debe coincidir la cantidad de columnas con la cantidad de valores en `ascending`. Si ordenamos por dos columnas, debemos indicar dos valores: uno para cada criterio.

## Combinar filtros y ordenamiento

En muchos análisis no ordenamos todo el dataset, sino un subconjunto de filas.

Por ejemplo, podemos querer ver solamente los productos de la categoría `"Tecnologia"` y ordenarlos por precio de mayor a menor.

Para hacerlo, primero filtramos y luego aplicamos `sort_values()` al resultado.

In [14]:
df[df["categoria"] == "Tecnologia"].sort_values("precio", ascending=False)

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04

La primera parte de la instrucción filtra el `DataFrame`:

```python
df[df["categoria"] == "Tecnologia"]
```

Luego, sobre ese resultado filtrado, aplicamos:

```python
.sort_values("precio", ascending=False)
```

De esta manera obtenemos únicamente las ventas de la categoría `"Tecnologia"`, ordenadas desde el precio más alto hasta el precio más bajo.

También podemos combinar un filtro más específico con ordenamiento. Por ejemplo, podemos seleccionar las ventas realizadas en la sucursal `"Centro"` y ordenarlas por `cantidad_vendida` de mayor a menor.

In [15]:
df[df["sucursal"] == "Centro"].sort_values("cantidad_vendida", ascending=False)

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03

Este encadenamiento es muy común en Pandas. Primero reducimos el dataset con un filtro y luego organizamos el resultado para leerlo mejor.

La estructura general es:

```python
df[condición].sort_values("columna")
```

o, si queremos ordenar de mayor a menor:

```python
df[condición].sort_values("columna", ascending=False)
```

Esta forma de trabajo permite responder preguntas más precisas. No solo preguntamos qué filas cumplen una condición, sino también cómo se ordenan esas filas según una variable relevante.

## Seleccionar columnas después de ordenar

Cuando ordenamos un `DataFrame`, Pandas muestra todas las columnas. Sin embargo, muchas veces nos interesa presentar solamente algunas.

Por ejemplo, si queremos ver los productos más caros, tal vez no necesitemos mostrar la fecha o la forma de pago. Podría alcanzarnos con ver el producto, la categoría y el precio.

Podemos ordenar primero y luego seleccionar algunas columnas:

In [16]:
df.sort_values("precio", ascending=False)[["producto", "categoria", "precio"]]

        producto     categoria  precio
5    Calculadora    Tecnologia   18500
8    Guardapolvo  Indumentaria   14500
10      Pendrive    Tecnologia    9800
2        Mochila    Accesorios    8500
6    Auriculares    Tecnologia    7600
14        Agenda      Libreria    4300
4     Cartuchera    Accesorios    3200
9         Compas      Libreria    2600
7   Resaltadores      Libreria    2100
0       Cuaderno      Libreria    1200
11       Carpeta      Libreria     950
3          Regla      Libreria     500
1       Lapicera      Libreria     350
12          Goma      Libreria     300
13         Lapiz      Libreria     250

Esta instrucción se lee de izquierda a derecha. Primero ordenamos el `DataFrame` por `precio` de mayor a menor. Luego, del resultado ordenado, seleccionamos solamente las columnas `producto`, `categoria` y `precio`.

También podemos hacer algo parecido con la cantidad vendida:

In [17]:
df.sort_values("cantidad_vendida", ascending=False)[
    ["producto", "categoria", "cantidad_vendida"]
]

        producto     categoria  cantidad_vendida
13         Lapiz      Libreria                50
1       Lapicera      Libreria                40
12          Goma      Libreria                30
3          Regla      Libreria                25
11       Carpeta      Libreria                18
0       Cuaderno      Libreria                15
7   Resaltadores      Libreria                12
9         Compas      Libreria                10
14        Agenda      Libreria                 9
4     Cartuchera    Accesorios                 8
10      Pendrive    Tecnologia                 7
6    Auriculares    Tecnologia                 6
2        Mochila    Accesorios                 5
8    Guardapolvo  Indumentaria                 4
5    Calculadora    Tecnologia                 3

En este caso, la tabla resultante permite identificar rápidamente qué productos tuvieron mayor cantidad de unidades vendidas.

Esta forma de trabajo es útil cuando queremos construir salidas más limpias. En lugar de mostrar toda la tabla, podemos quedarnos con las columnas necesarias para responder una pregunta concreta.

También podríamos combinar filtro, ordenamiento y selección de columnas:

In [18]:
df[df["categoria"] == "Libreria"].sort_values(
    "cantidad_vendida",
    ascending=False
)[["producto", "categoria", "cantidad_vendida", "sucursal"]]

        producto categoria  cantidad_vendida sucursal
13         Lapiz  Libreria                50   Centro
1       Lapicera  Libreria                40   Centro
12          Goma  Libreria                30      Sur
3          Regla  Libreria                25      Sur
11       Carpeta  Libreria                18    Norte
0       Cuaderno  Libreria                15   Centro
7   Resaltadores  Libreria                12   Centro
9         Compas  Libreria                10      Sur
14        Agenda  Libreria                 9      Sur

Esta instrucción selecciona solamente las ventas de la categoría `"Libreria"`, las ordena por `cantidad_vendida` de mayor a menor y muestra algunas columnas relevantes.

Cuando las operaciones se encadenan, el orden importa. En este ejemplo, primero filtramos, después ordenamos y finalmente seleccionamos columnas para presentar el resultado de manera más clara.

## Guardar un resultado ordenado

Cuando usamos `sort_values()`, Pandas muestra el `DataFrame` ordenado, pero no modifica el `DataFrame` original.

Por ejemplo, podemos ordenar por precio de mayor a menor:

In [19]:
df.sort_values("precio", ascending=False)

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07

Si después mostramos nuevamente `df`, veremos que el orden original se conserva.

In [20]:
df

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08

Esto ocurre porque `sort_values()` devuelve un nuevo resultado ordenado, pero no cambia automáticamente el `DataFrame` sobre el que se aplicó.

Si queremos reutilizar el resultado ordenado más adelante, podemos guardarlo en una nueva variable.

In [21]:
ventas_por_precio = df.sort_values("precio", ascending=False)

ventas_por_precio

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07

Ahora `ventas_por_precio` contiene el dataset ordenado por precio de mayor a menor, mientras que `df` sigue conservando el orden original.

Esta forma de trabajo es recomendable porque evita modificar accidentalmente los datos originales. Podemos tener distintas versiones ordenadas del mismo dataset, según la pregunta que queramos responder.

Por ejemplo:

In [22]:
ventas_por_cantidad = df.sort_values("cantidad_vendida", ascending=False)

ventas_por_cantidad

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03

En este caso, la variable `ventas_por_cantidad` contiene las ventas ordenadas según la cantidad vendida, de mayor a menor.

Guardar resultados en variables con nombres claros ayuda a que el análisis sea más legible. Un nombre como `ventas_por_precio` o `ventas_por_cantidad` permite entender rápidamente qué contiene cada objeto.

## Ordenar por índice

Hasta ahora ordenamos el `DataFrame` usando los valores de una columna. Para eso usamos `sort_values()`.

Pero Pandas también permite ordenar un `DataFrame` según su índice. Para eso usamos `sort_index()`.

Primero veamos un ejemplo. Podemos crear un `DataFrame` ordenado por precio de mayor a menor:

In [23]:
ventas_por_precio = df.sort_values("precio", ascending=False)

ventas_por_precio

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07

Observemos que las filas aparecen ordenadas por precio, pero el índice conserva las etiquetas originales. Por eso, al mirar la columna del índice, los valores pueden aparecer en un orden como `5`, `8`, `10`, `2`, etc.

Si queremos ordenar nuevamente ese resultado según el índice, podemos usar `sort_index()`.

In [24]:
ventas_por_precio.sort_index()

,producto,categoria,precio,cantidad_vendida,sucursal,forma_pago,fecha
0,Cuaderno,Libreria,1200,15,Centro,Efectivo,2024-03-01
1,Lapicera,Libreria,350,40,Centro,Debito,2024-03-01
2,Mochila,Accesorios,8500,5,Norte,Credito,2024-03-02
3,Regla,Libreria,500,25,Sur,Efectivo,2024-03-02
4,Cartuchera,Accesorios,3200,8,Norte,Debito,2024-03-03
5,Calculadora,Tecnologia,18500,3,Centro,Credito,2024-03-03
6,Auriculares,Tecnologia,7600,6,Sur,Credito,2024-03-04
7,Resaltadores,Libreria,2100,12,Centro,Debito,2024-03-04
8,Guardapolvo,Indumentaria,14500,4,Norte,Credito,2024-03-05
9,Compas,Libreria,2600,10,Sur,Efectivo,2024-03-05
10,Pendrive,Tecnologia,9800,7,Centro,Debito,2024-03-06
11,Carpeta,Libreria,950,18,Norte,Efectivo,2024-03-06
12,Goma,Libreria,300,30,Sur,Efectivo,2024-03-07
13,Lapiz,Libreria,250,50,Centro,Debito,2024-03-07
14,Agenda,Libreria,4300,9,Sur,Credito,2024-03-08

Ahora las filas vuelven a aparecer ordenadas según las etiquetas del índice.

La diferencia principal es esta:

```text
sort_values() → ordena según los valores de una o más columnas
sort_index()  → ordena según el índice
```

En este punto no necesitamos profundizar demasiado en el índice. Más adelante lo vamos a estudiar con más detalle. Por ahora, alcanza con reconocer que Pandas puede ordenar tanto por valores de columnas como por etiquetas del índice.

## Errores frecuentes al ordenar datos

Al ordenar datos con Pandas, pueden aparecer algunos errores o confusiones frecuentes.

Uno de los errores más comunes es escribir mal el nombre de la columna. Por ejemplo, nuestro `DataFrame` tiene una columna llamada `precio`, con minúscula. Si intentamos ordenar usando `"Precio"` con mayúscula inicial, Pandas no podrá encontrar esa columna.

In [25]:
# Esta instrucción produciría un error porque la columna se llama "precio", no "Precio".
# df.sort_values("Precio")

Para evitar este problema, conviene revisar los nombres de las columnas antes de ordenar.

In [26]:
df.columns

Index(['producto', 'categoria', 'precio', 'cantidad_vendida', 'sucursal',
       'forma_pago', 'fecha'],
      dtype='object')

Otro error frecuente es olvidar `ascending=False` cuando queremos ordenar de mayor a menor. Si escribimos:

```python
df.sort_values("precio")
```

Pandas ordena de menor a mayor, porque ese es el comportamiento por defecto. Si queremos ver primero los precios más altos, debemos escribir:

```python
df.sort_values("precio", ascending=False)
```

También puede ocurrir que pensemos que `sort_values()` modifica el `DataFrame` original. Sin embargo, como vimos antes, el método devuelve un resultado ordenado, pero no cambia automáticamente `df`.

Por eso, si queremos conservar el resultado ordenado, conviene guardarlo en una nueva variable:

```python
ventas_ordenadas = df.sort_values("precio", ascending=False)
```

Finalmente, cuando ordenamos por varias columnas, debemos cuidar que la lista de columnas y la lista de valores de ascending tengan la misma longitud.

```python
# Esta instrucción produciría un error porque se indican dos columnas,
# pero solo un valor para ascending dentro de una lista.

# df.sort_values(["categoria", "precio"], ascending=[True])
```

La forma correcta sería:

```python
df.sort_values(["categoria", "precio"], ascending=[True, False])
```

En general, para ordenar datos de manera segura conviene revisar tres cosas: que el nombre de la columna exista, que el sentido del ordenamiento sea el que necesitamos y que sepamos si queremos solamente ver el resultado ordenado o guardarlo para usarlo más adelante.

## Resumen del capítulo

En este capítulo aprendimos a ordenar datos en un `DataFrame`.

Ordenar datos significa reorganizar las filas según los valores de una o más columnas. Esta operación no cambia el significado de los datos, pero puede facilitar mucho su lectura. Al ordenar una tabla podemos detectar rápidamente valores altos, valores bajos, rankings, agrupamientos visuales o registros que conviene revisar con más atención.

La herramienta principal que usamos fue `sort_values()`.

Primero ordenamos el `DataFrame` según una sola columna:

```python
df.sort_values("precio")
```

Por defecto, Pandas ordena de manera ascendente. En una columna numérica, eso significa de menor a mayor. Para ordenar en sentido descendente usamos `ascending=False`:

```python
df.sort_values("precio", ascending=False)
```

También vimos que podemos ordenar por otras columnas numéricas, como `cantidad_vendida`, y por columnas de texto, como `producto`, `categoria` o `sucursal`. En las columnas textuales, Pandas ordena alfabéticamente.

Luego aprendimos a ordenar por más de una columna. Para eso pasamos una lista de columnas a `sort_values()`:

```python
df.sort_values(["categoria", "precio"])
```

En este caso, Pandas ordena primero por `categoria` y, dentro de cada categoría, ordena por `precio`.

También vimos que podemos indicar distintos sentidos de ordenamiento para cada columna:

```python
df.sort_values(
    ["categoria", "precio"],
    ascending=[True, False]
)
```

Después combinamos filtros y ordenamiento. Esta forma de trabajo permite seleccionar primero un subconjunto del dataset y luego organizar ese resultado:

```python
df[df["categoria"] == "Tecnologia"].sort_values("precio", ascending=False)
```

Más adelante vimos que también podemos ordenar y seleccionar solamente algunas columnas para construir salidas más limpias:

```python
df.sort_values("precio", ascending=False)[["producto", "categoria", "precio"]]
```

Otro punto importante fue que `sort_values()` no modifica automáticamente el `DataFrame` original. Si queremos conservar un resultado ordenado, conviene guardarlo en una nueva variable:

```python
ventas_por_precio = df.sort_values("precio", ascending=False)
```

Finalmente presentamos `sort_index()`, que permite ordenar un `DataFrame` según su índice:

```python
ventas_por_precio.sort_index()
```

La idea principal de este capítulo fue:

```text
Ordenar datos nos ayuda a leer, comparar y detectar valores importantes dentro de un DataFrame.
```

Ordenar no reemplaza el análisis, pero muchas veces es un paso necesario para observar mejor la información y preparar resultados más claros.

## Próximo paso

Ya sabemos seleccionar columnas, seleccionar filas, filtrar registros usando condiciones y ordenar un `DataFrame`.

El siguiente paso será aprender a identificar valores extremos y primeros rankings de manera más directa. Para eso vamos a trabajar con herramientas como `head()`, `tail()`, `nlargest()` y `nsmallest()`.

Estas operaciones nos permitirán responder preguntas como cuáles son los productos más caros, cuáles son los más baratos, cuáles tienen mayor cantidad vendida o cuáles aparecen al final de un ordenamiento determinado.