<a href="https://colab.research.google.com/github/VintaBytes/Ciencia-de-datos/blob/main/Ciencia%20De%20Datos%20Con%20Python/CuadernosColab/CienciaDeDatos_Cap%C3%ADtulo004_Selecci%C3%B3n_de_filas_en_un_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Abrir en Colab"/></a>

# Capítulo 4 — Selección de filas en un DataFrame

## Breve repaso

En el capítulo anterior aprendimos a seleccionar columnas de un `DataFrame`.

Vimos que una columna puede seleccionarse usando su nombre entre corchetes, por ejemplo `df["precio"]`, y que esa operación devuelve una `Series`. También vimos que, si usamos doble corchete, como en `df[["precio"]]`, Pandas devuelve un `DataFrame` con una sola columna.

Además, aprendimos a seleccionar varias columnas al mismo tiempo y a guardar esas selecciones en nuevas variables. Esa operación nos permitió hacer un primer recorte del dataset, eligiendo solamente las variables necesarias para una pregunta de análisis.

En este capítulo vamos a trabajar con otra forma de selección: la selección de filas.

Si las columnas representan variables, las filas representan observaciones, registros o casos. Por eso, seleccionar filas significa elegir qué registros del dataset queremos observar.

A lo largo del capítulo vamos a aprender a seleccionar filas por posición, a obtener una fila individual, a seleccionar rangos de filas y a reconocer la diferencia entre trabajar con una fila como `Series` o como `DataFrame`.

También vamos a empezar a preparar el camino para una herramienta muy importante de Pandas: `iloc`, que permite seleccionar datos usando posiciones numéricas.

Al finalizar este capítulo deberías poder:

- Seleccionar una fila de un `DataFrame` usando su posición.
- Seleccionar varias filas consecutivas.
- Comprender qué significa seleccionar por posición.
- Reconocer cuándo Pandas devuelve una `Series`.
- Reconocer cuándo Pandas devuelve un `DataFrame`.
- Usar `iloc` para seleccionar filas.
- Combinar una primera selección de filas y columnas usando posiciones.

## Dataset de trabajo

En este capítulo vamos a seguir usando el dataset de ventas de una librería.

Cada fila representa una venta registrada y cada columna describe una característica de esa venta. Como ya conocemos la estructura general del dataset, podemos concentrarnos en una nueva pregunta: cómo seleccionar filas específicas.

Recordemos que, mientras las columnas representan variables, las filas representan registros u observaciones. En este caso, cada fila representa una venta.

In [25]:
import pandas as pd

datos = {
    "producto": [
        "Cuaderno", "Lapicera", "Mochila", "Regla", "Cartuchera",
        "Cuaderno", "Marcadores", "Carpeta", "Goma", "Lapiz"
    ],
    "categoria": [
        "Libreria", "Libreria", "Accesorios", "Libreria", "Accesorios",
        "Libreria", "Libreria", "Libreria", "Libreria", "Libreria"
    ],
    "precio": [
        1200, 350, 8500, 500, 3200,
        1250, 1800, 950, 300, 250
    ],
    "cantidad_vendida": [
        15, 40, 5, 25, 8,
        12, 10, 18, 30, 50
    ],
    "sucursal": [
        "Centro", "Centro", "Norte", "Sur", "Norte",
        "Sur", "Centro", "Norte", "Sur", "Centro"
    ],
    "fecha": [
        "2024-03-01", "2024-03-01", "2024-03-02", "2024-03-02", "2024-03-03",
        "2024-03-03", "2024-03-04", "2024-03-04", "2024-03-05", "2024-03-05"
    ]
}

df = pd.DataFrame(datos)

df

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
7     Carpeta    Libreria     950                18    Norte  2024-03-04
8        Goma    Libreria     300                30      Sur  2024-03-05
9       Lapiz    Libreria     250                50   Centro  2024-03-05

Al mostrar el `DataFrame`, vemos nuevamente las 10 ventas registradas.

A la izquierda aparece el índice, que en este caso va de `0` a `9`. Ese índice nos permite identificar cada fila dentro del `DataFrame`. En este capítulo vamos a usarlo como referencia visual, pero el foco estará puesto en la selección por posición mediante `iloc`.

## Qué significa seleccionar filas

En un `DataFrame`, las columnas representan variables y las filas representan observaciones, registros o casos.

En nuestro dataset, cada fila representa una venta. Por eso, seleccionar una fila significa elegir una venta específica del conjunto de datos.

Por ejemplo, podríamos querer observar solamente la primera venta registrada, revisar las primeras tres ventas, mirar una venta que aparece en una posición determinada o comparar algunos registros puntuales.

Seleccionar filas es diferente de seleccionar columnas. Cuando seleccionamos columnas, elegimos variables. Cuando seleccionamos filas, elegimos registros.

En este capítulo vamos a comenzar con una forma de selección muy importante: la selección por posición.

La posición indica el lugar que ocupa una fila dentro del `DataFrame`. Como ocurre muchas veces en Python, las posiciones empiezan a contarse desde `0`. Entonces, la primera fila está en la posición `0`, la segunda fila está en la posición `1`, la tercera fila está en la posición `2`, y así sucesivamente.

En nuestro dataset, que tiene 10 filas, las posiciones van desde `0` hasta `9`.

Para seleccionar filas por posición vamos a usar `iloc`.

## Seleccionar una fila con `iloc`

`iloc` permite seleccionar filas y columnas usando posiciones numéricas. La palabra `iloc` puede pensarse como una abreviatura de *integer location*, es decir, ubicación mediante números enteros.

Para seleccionar una fila por su posición, escribimos el nombre del `DataFrame`, luego `.iloc[]`, y dentro de los corchetes indicamos la posición de la fila que queremos obtener. Por ejemplo, para seleccionar la primera fila del `DataFrame`, usamos la posición `0`.

In [26]:
df.iloc[0]

producto              Cuaderno
categoria             Libreria
precio                    1200
cantidad_vendida            15
sucursal                Centro
fecha               2024-03-01
Name: 0, dtype: object

La salida muestra la información completa de la primera venta registrada. Como estamos seleccionando una sola fila, Pandas devuelve una `Series`.

En este caso, los nombres de las columnas aparecen a la izquierda y los valores de esa fila aparecen a la derecha. Es decir, la fila seleccionada se muestra como una estructura de una sola dimensión.

La posición `0` corresponde a la primera fila porque Pandas, al igual que Python, comienza a contar desde cero.

In [27]:
df.iloc[1]

producto              Lapicera
categoria             Libreria
precio                     350
cantidad_vendida            40
sucursal                Centro
fecha               2024-03-01
Name: 1, dtype: object

En este segundo ejemplo seleccionamos la fila ubicada en la posición `1`, que corresponde a la segunda fila del `DataFrame`.

Esto puede resultar extraño al principio si estamos acostumbrados a contar desde 1, pero es una convención muy frecuente en programación. La primera posición es `0`, la segunda es `1`, la tercera es `2`, y así sucesivamente.

## Posición e índice no siempre son lo mismo

En nuestro dataset actual, el índice coincide visualmente con la posición de cada fila. La primera fila tiene índice `0`, la segunda tiene índice `1`, la tercera tiene índice `2`, y así sucesivamente.

Por eso, al principio puede parecer que índice y posición son lo mismo. Sin embargo, no siempre ocurre así.

La **posición** indica el lugar que ocupa una fila dentro del `DataFrame`: primera, segunda, tercera, etc. En cambio, el **índice** es una etiqueta que Pandas usa para identificar las filas. Muchas veces el índice es numérico y empieza en `0`, pero también puede estar formado por otros valores, como códigos, fechas, nombres o identificadores.

`iloc` trabaja con posiciones, no con etiquetas del índice.

Esto significa que cuando escribimos:

```python
df.iloc[0]
```

estamos pidiendo la fila que está en la primera posición, no necesariamente la fila cuyo índice se llama `0`.

En este capítulo vamos a concentrarnos en la selección por posición. Más adelante vamos a trabajar con más detalle la selección por etiquetas y veremos por qué esta diferencia es importante.

## Seleccionar la última fila

Así como en las listas de Python, `iloc` también permite usar posiciones negativas.

La posición `-1` representa la última fila del `DataFrame`.

In [28]:
df.iloc[-1]

producto                 Lapiz
categoria             Libreria
precio                     250
cantidad_vendida            50
sucursal                Centro
fecha               2024-03-05
Name: 9, dtype: object

La salida muestra la última venta registrada en el dataset.

También podemos usar `-2` para seleccionar la anteúltima fila:

In [29]:
df.iloc[-2]

producto                  Goma
categoria             Libreria
precio                     300
cantidad_vendida            30
sucursal                   Sur
fecha               2024-03-05
Name: 8, dtype: object

Las posiciones negativas son útiles cuando queremos acceder al final de una tabla sin contar manualmente cuántas filas tiene.

Podemos resumirlo así:

```text
df.iloc[0]   → primera fila
df.iloc[1]   → segunda fila
df.iloc[-1]  → última fila
df.iloc[-2]  → anteúltima fila
```

## Seleccionar varias filas consecutivas

Hasta ahora seleccionamos una sola fila por vez. Pero muchas veces queremos obtener varias filas consecutivas. Para eso podemos usar un rango dentro de `iloc`.

Por ejemplo, si queremos seleccionar las primeras tres filas, escribimos:

In [30]:
df.iloc[0:3]

   producto   categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno    Libreria    1200                15   Centro  2024-03-01
1  Lapicera    Libreria     350                40   Centro  2024-03-01
2   Mochila  Accesorios    8500                 5    Norte  2024-03-02

La notación `0:3` indica un rango de posiciones.

En Python, los rangos incluyen el primer valor, pero no incluyen el último. Por eso, `0:3` selecciona las posiciones `0`, `1` y `2`.

Dicho de otra manera:

```text
df.iloc[0:3] → selecciona desde la posición 0 hasta antes de la posición 3
```

El resultado es un `DataFrame`, no una `Series`, porque estamos seleccionando varias filas.

Podemos probar otros rangos:

In [31]:
df.iloc[3:7]

     producto   categoria  precio  cantidad_vendida sucursal       fecha
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04

En este caso seleccionamos las filas ubicadas en las posiciones `3`, `4`, `5` y `6`.

También podemos omitir el primer valor del rango si queremos comenzar desde el principio:

In [32]:
df.iloc[:5]

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03

Esta instrucción selecciona desde el comienzo del `DataFrame` hasta antes de la posición `5`. Es decir, devuelve las primeras cinco filas.

También podemos omitir el segundo valor si queremos seleccionar desde una posición hasta el final:

In [33]:
df.iloc[5:]

     producto categoria  precio  cantidad_vendida sucursal       fecha
5    Cuaderno  Libreria    1250                12      Sur  2024-03-03
6  Marcadores  Libreria    1800                10   Centro  2024-03-04
7     Carpeta  Libreria     950                18    Norte  2024-03-04
8        Goma  Libreria     300                30      Sur  2024-03-05
9       Lapiz  Libreria     250                50   Centro  2024-03-05

Esta instrucción selecciona desde la posición `5` hasta el final del `DataFrame`.

Esta forma de selección es muy útil cuando queremos revisar partes consecutivas de una tabla sin mostrar el dataset completo.

## Seleccionar una fila como DataFrame

Cuando usamos `iloc` con una sola posición, Pandas devuelve una `Series`. Por ejemplo:

In [34]:
df.iloc[0]

producto              Cuaderno
categoria             Libreria
precio                    1200
cantidad_vendida            15
sucursal                Centro
fecha               2024-03-01
Name: 0, dtype: object

Esa salida representa una sola fila, pero no se muestra como tabla. Los nombres de las columnas aparecen como etiquetas y los valores de la fila aparecen a continuación.

A veces, sin embargo, queremos seleccionar una sola fila y conservar el formato de `DataFrame`. Para eso podemos usar una lista con una sola posición:

In [35]:
df.iloc[[0]]

   producto categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno  Libreria    1200                15   Centro  2024-03-01

La diferencia está en los corchetes. Cuando escribimos:

```python
df.iloc[0]
```

obtenemos una `Series`. En cambio, cuando escribimos:

```python
df.iloc[[0]]
```

obtenemos un `DataFrame` con una sola fila. Podemos verificarlo usando `type()`:

In [36]:
print(type(df.iloc[0]))

<class 'pandas.core.series.Series'>

In [37]:
print(type(df.iloc[[0]]))

<class 'pandas.core.frame.DataFrame'>

Esta diferencia es parecida a la que vimos al seleccionar columnas. En Pandas, la forma en que escribimos la selección puede cambiar el tipo de objeto que obtenemos.

Podemos resumirlo así:

```text
df.iloc[0]    → selecciona una fila como Series

df.iloc[[0]]  → selecciona una fila como DataFrame
```

Cuando queremos conservar la forma de tabla, usamos una lista de posiciones, aunque esa lista tenga un solo elemento.

## Seleccionar filas no consecutivas

Con `iloc` también podemos seleccionar varias filas que no estén una al lado de la otra. Para eso usamos una lista de posiciones.

Por ejemplo, si queremos seleccionar la primera, la cuarta y la última fila del `DataFrame`, podemos escribir:

In [38]:
df.iloc[[0, 3, 9]]

   producto categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno  Libreria    1200                15   Centro  2024-03-01
3     Regla  Libreria     500                25      Sur  2024-03-02
9     Lapiz  Libreria     250                50   Centro  2024-03-05

En este caso, Pandas devuelve un `DataFrame` con las filas ubicadas en las posiciones `0`, `3` y `9`.

La lista de posiciones se escribe entre corchetes:

```python
[0, 3, 9]
```

y esa lista se coloca dentro de `iloc`:

```python
df.iloc[[0, 3, 9]]
```

Esta forma de selección es útil cuando queremos observar registros puntuales sin seleccionar todo un rango.

También podemos seleccionar, por ejemplo, la segunda, la quinta y la octava fila:

In [39]:
df.iloc[[1, 4, 7]]

     producto   categoria  precio  cantidad_vendida sucursal       fecha
1    Lapicera    Libreria     350                40   Centro  2024-03-01
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
7     Carpeta    Libreria     950                18    Norte  2024-03-04

Recordemos que las posiciones comienzan en `0`. Por eso, la segunda fila está en la posición `1`, la quinta fila está en la posición `4` y la octava fila está en la posición `7`.

Cuando usamos una lista de posiciones, el resultado conserva el formato de `DataFrame`, aunque seleccionemos una sola fila o varias filas separadas.

## Seleccionar filas y columnas con `iloc`

Hasta ahora usamos `iloc` para seleccionar filas. Pero `iloc` también permite seleccionar filas y columnas al mismo tiempo usando posiciones numéricas.

La estructura general es:

```python
df.iloc[filas, columnas]
```

El primer valor indica qué filas queremos seleccionar. El segundo valor indica qué columnas queremos seleccionar.

Por ejemplo, si queremos seleccionar la primera fila y la primera columna, podemos escribir:

In [40]:
df.iloc[0, 0]

'Cuaderno'

La salida es un único valor. En nuestro dataset, ese valor corresponde al producto de la primera venta.

También podemos seleccionar una fila completa y algunas columnas específicas. Por ejemplo:

In [41]:
df.iloc[0, [0, 2, 3]]

producto            Cuaderno
precio                  1200
cantidad_vendida          15
Name: 0, dtype: object

En este caso seleccionamos la fila ubicada en la posición `0`, y dentro de esa fila seleccionamos las columnas ubicadas en las posiciones `0`, `2` y `3`.

Para entender mejor esas posiciones, recordemos el orden de las columnas:

In [42]:
list(df.columns)

['producto', 'categoria', 'precio', 'cantidad_vendida', 'sucursal', 'fecha']

La lista de columnas nos muestra que:

```text
posición 0 → producto
posición 1 → categoria
posición 2 → precio
posición 3 → cantidad_vendida
posición 4 → sucursal
posición 5 → fecha
```

Entonces:

```python
df.iloc[0, [0, 2, 3]]
```

selecciona, para la primera fila, las columnas `producto`, `precio` y `cantidad_vendida`.

También podemos seleccionar varias filas y varias columnas:

In [43]:
df.iloc[0:4, [0, 2, 3]]

   producto  precio  cantidad_vendida
0  Cuaderno    1200                15
1  Lapicera     350                40
2   Mochila    8500                 5
3     Regla     500                25

Esta instrucción selecciona las filas ubicadas desde la posición `0` hasta antes de la posición `4`, y las columnas ubicadas en las posiciones `0`, `2` y `3`.

El resultado es un `DataFrame` con las primeras cuatro ventas y solo algunas columnas.

Esta forma de selección es potente, pero exige prestar atención a las posiciones. Por eso, cuando trabajamos con columnas, muchas veces resulta más claro seleccionarlas por nombre. Más adelante vamos a combinar distintas formas de selección para escribir código más legible.

## Errores frecuentes al usar `iloc`

Cuando usamos `iloc`, debemos recordar que estamos trabajando con posiciones numéricas. Esto significa que no escribimos nombres de columnas ni etiquetas del índice, sino números que indican ubicaciones dentro del `DataFrame`.

Por ejemplo, esta instrucción es correcta:

In [44]:
df.iloc[0, 2]

np.int64(1200)

En este caso seleccionamos el valor ubicado en la primera fila y en la tercera columna. Recordemos que la primera posición es `0`, por eso la columna en posición `2` es la tercera columna del `DataFrame`.

Un error frecuente sería intentar usar el nombre de una columna dentro de `iloc`:

In [45]:
# Esta instrucción produce un error porque iloc trabaja con posiciones, no con nombres.
# df.iloc[0, "precio"

Si queremos seleccionar usando nombres de columnas, necesitamos otra herramienta. Más adelante vamos a trabajar con `loc`, que permite seleccionar usando etiquetas o nombres.

Otro error frecuente es pedir una posición que no existe. Nuestro dataset tiene 10 filas, por lo tanto sus posiciones van desde `0` hasta `9`. Si intentamos seleccionar la posición `10`, Pandas mostrará un error porque esa fila no existe.

In [46]:
# Esta instrucción produce un error porque no existe una fila en la posición 10.
# df.iloc[10]

Estos errores son normales al comenzar a trabajar con Pandas. La clave es recordar qué tipo de referencia espera cada herramienta.

Con `iloc`, usamos posiciones numéricas. Para evitar confusiones, puede ser útil revisar primero el tamaño del `DataFrame` con `shape` y el orden de las columnas con `list(df.columns)`.

## Resumen del capítulo

En este capítulo aprendimos a seleccionar filas de un `DataFrame` usando `iloc`.

Mientras que en el capítulo anterior seleccionamos columnas, es decir, variables, ahora trabajamos con filas, que representan registros u observaciones. En nuestro dataset, cada fila corresponde a una venta registrada.

Vimos que `iloc` permite seleccionar datos usando posiciones numéricas. La primera fila está en la posición `0`, la segunda en la posición `1`, la tercera en la posición `2`, y así sucesivamente. Esta forma de contar desde cero es habitual en Python y también aparece en muchas operaciones de Pandas.

Primero seleccionamos una fila individual:


```python
df.iloc[0]
```

Esa instrucción devuelve una `Series`, porque estamos seleccionando una sola fila.

Luego vimos que también podemos seleccionar una fila conservando el formato de tabla:

```python
df.iloc[[0]]
```

En ese caso, Pandas devuelve un `DataFrame` con una sola fila.

También aprendimos a seleccionar varias filas consecutivas usando rangos:

```python
df.iloc[0:3]
```

y filas no consecutivas usando listas de posiciones:

```python
df.iloc[[0, 3, 9]]
```

Más adelante combinamos filas y columnas dentro de `iloc`, usando la estructura:

```python
df.iloc[filas, columnas]
```

Por ejemplo:

```python
df.iloc[0:4, [0, 2, 3]]
```

selecciona las primeras cuatro filas y las columnas ubicadas en las posiciones `0`, `2` y `3`.

Una idea importante de este capítulo fue distinguir entre posición e índice. En nuestro dataset actual parecen coincidir, pero no siempre será así. `iloc` trabaja con posiciones, no con etiquetas del índice.

La idea principal que conviene recordar es:

```text
iloc permite seleccionar filas y columnas usando posiciones numéricas.
```

Esta herramienta es muy útil cuando queremos acceder a partes específicas de un `DataFrame` según su ubicación.

## Próximo paso

Ya sabemos seleccionar columnas y también sabemos seleccionar filas usando posiciones numéricas.

El siguiente paso será aprender a seleccionar datos usando etiquetas, nombres de columnas e índices. Para eso vamos a trabajar con `loc`, una herramienta central de Pandas que permite escribir selecciones más expresivas cuando conocemos los nombres de las columnas o las etiquetas de las filas.

A medida que avancemos, vamos a combinar estas formas de selección para construir consultas cada vez más precisas sobre nuestros datasets.