<a href="https://colab.research.google.com/github/VintaBytes/Ciencia-de-datos/blob/main/CienciaDeDatosConPython/CuadernosColab/CienciaDeDatos_Cap%C3%ADtulo003_Selecci%C3%B3n_de_columnas_en_un_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Abrir en Colab"/></a>

# Capítulo 03 — Selección de columnas en un DataFrame

## Breve repaso

En el capítulo anterior aprendimos a realizar una primera inspección de un `DataFrame`.

Vimos cómo observar sus primeras y últimas filas, revisar sus dimensiones, consultar los nombres de las columnas, reconocer el índice, mirar los tipos de datos y obtener resúmenes generales con herramientas como `info()` y `describe()`.

Ese primer recorrido nos permitió construir una idea importante: antes de analizar un dataset, necesitamos conocer su estructura.

En este capítulo vamos a dar un paso más. Vamos a aprender a seleccionar columnas de un `DataFrame`.

Seleccionar columnas es una operación básica, pero fundamental. Muchas veces no necesitamos trabajar con toda la tabla, sino con una o varias variables específicas. Por ejemplo, podemos querer analizar solamente los precios, revisar las fechas, observar las sucursales o comparar dos columnas entre sí.

A lo largo del capítulo vamos a trabajar con un dataset sencillo de ventas y vamos a ver cómo seleccionar una columna, cómo seleccionar varias columnas y qué diferencia hay entre obtener una `Series` y obtener otro `DataFrame`.

Al finalizar este capítulo deberías poder:

- Seleccionar una columna de un `DataFrame`.
- Seleccionar varias columnas al mismo tiempo.
- Reconocer cuándo Pandas devuelve una `Series`.
- Reconocer cuándo Pandas devuelve un `DataFrame`.
- Guardar una selección de columnas en una nueva variable.
- Evitar algunos errores frecuentes al escribir nombres de columnas.

## Dataset de trabajo

En este capítulo vamos a seguir trabajando con un dataset pequeño de ventas de una librería.

Cada fila representa una venta registrada. Cada columna describe una característica de esa venta: el producto, la categoría, el precio unitario, la cantidad vendida, la sucursal y la fecha.

Usar un dataset ya conocido nos permite concentrarnos en el tema nuevo: la selección de columnas.

In [1]:
import pandas as pd

datos = {
    "producto": [
        "Cuaderno", "Lapicera", "Mochila", "Regla", "Cartuchera",
        "Cuaderno", "Marcadores", "Carpeta", "Goma", "Lapiz"
    ],
    "categoria": [
        "Libreria", "Libreria", "Accesorios", "Libreria", "Accesorios",
        "Libreria", "Libreria", "Libreria", "Libreria", "Libreria"
    ],
    "precio": [
        1200, 350, 8500, 500, 3200,
        1250, 1800, 950, 300, 250
    ],
    "cantidad_vendida": [
        15, 40, 5, 25, 8,
        12, 10, 18, 30, 50
    ],
    "sucursal": [
        "Centro", "Centro", "Norte", "Sur", "Norte",
        "Sur", "Centro", "Norte", "Sur", "Centro"
    ],
    "fecha": [
        "2024-03-01", "2024-03-01", "2024-03-02", "2024-03-02", "2024-03-03",
        "2024-03-03", "2024-03-04", "2024-03-04", "2024-03-05", "2024-03-05"
    ]
}

df = pd.DataFrame(datos)

df

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
7     Carpeta    Libreria     950                18    Norte  2024-03-04
8        Goma    Libreria     300                30      Sur  2024-03-05
9       Lapiz    Libreria     250                50   Centro  2024-03-05

Antes de avanzar, recordemos brevemente qué contiene este `DataFrame`.

Tenemos 10 filas y 6 columnas. Las columnas son:

```text
producto
categoria
precio
cantidad_vendida
sucursal
fecha
```

A partir de ahora vamos a aprender a quedarnos solamente con algunas de esas columnas, según la pregunta que queramos responder.

## Qué significa seleccionar columnas

Un `DataFrame` puede tener muchas columnas. Algunas pueden ser necesarias para una pregunta determinada y otras no.

Seleccionar columnas significa quedarnos solamente con una parte vertical de la tabla.

Por ejemplo, si queremos analizar los precios, no necesitamos mirar todas las columnas del dataset. Podemos seleccionar solamente la columna `precio`.

Si queremos comparar productos y precios, podemos seleccionar dos columnas:

```text
producto
precio
```

Y si queremos estudiar las ventas por sucursal, tal vez nos interesen estas columnas:

```text
sucursal
producto
cantidad_vendida
```

Seleccionar columnas no elimina información del `DataFrame` original. Solamente nos permite crear una vista o una nueva variable con las columnas que queremos observar.

Esta operación es muy frecuente porque, en datasets reales, podemos tener decenas o cientos de columnas. En esos casos, seleccionar solo las variables relevantes hace que el análisis sea más claro y manejable.

## Seleccionar una columna

Para seleccionar una columna de un `DataFrame`, escribimos el nombre del `DataFrame`, seguido del nombre de la columna entre corchetes.

Por ejemplo, si queremos seleccionar la columna `precio`, escribimos:

In [2]:
df["precio"]

0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250
Name: precio, dtype: int64

La salida muestra todos los valores de la columna `precio`.

En este caso, Pandas nos devuelve una estructura de una sola dimensión llamada `Series`.

Una `Series` puede pensarse como una columna individual de datos. Tiene valores y también conserva el índice del `DataFrame` original.

Si observamos la salida, veremos algo parecido a esto:

```text
0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250
Name: precio, dtype: int64
```

A la izquierda aparece el índice de cada fila. A la derecha aparecen los valores de la columna `precio`.

Al final, Pandas indica el nombre de la `Series` y su tipo de dato:

```text
Name: precio, dtype: int64
```

Esto nos dice que la columna se llama `precio` y que sus valores son números enteros.

## Seleccionar otras columnas

La misma forma de selección sirve para cualquier columna del `DataFrame`.

Por ejemplo, podemos seleccionar la columna `producto`:

In [3]:
df["producto"]

0      Cuaderno
1      Lapicera
2       Mochila
3         Regla
4    Cartuchera
5      Cuaderno
6    Marcadores
7       Carpeta
8          Goma
9         Lapiz
Name: producto, dtype: object

En este caso, Pandas devuelve una `Series` con los nombres de los productos vendidos.

También podemos seleccionar la columna `sucursal`:

In [4]:
df["sucursal"]

0    Centro
1    Centro
2     Norte
3       Sur
4     Norte
5       Sur
6    Centro
7     Norte
8       Sur
9    Centro
Name: sucursal, dtype: object

O la columna `cantidad_vendida`:

In [5]:
df["cantidad_vendida"]

0    15
1    40
2     5
3    25
4     8
5    12
6    10
7    18
8    30
9    50
Name: cantidad_vendida, dtype: int64

La estructura general siempre es la misma:

```text
df["nombre_de_la_columna"]
```

Donde `df` es el nombre del `DataFrame` y `"nombre_de_la_columna"` es el nombre exacto de la columna que queremos seleccionar.

Es importante escribir el nombre de la columna exactamente como aparece en el `DataFrame`. Pandas distingue entre mayúsculas y minúsculas, y también tiene en cuenta espacios, guiones bajos y otros caracteres.

Por ejemplo, en nuestro dataset la columna se llama:

```text
cantidad_vendida
```

No se llama:

```text
cantidad vendida
Cantidad_vendida
cantidad_Vendida
cantidad
```

Si escribimos mal el nombre de una columna, Pandas no podrá encontrarla y mostrará un error.

## Errores frecuentes al seleccionar columnas

Cuando seleccionamos una columna, el nombre debe coincidir exactamente con el nombre que aparece en el `DataFrame`.

Si escribimos un nombre incorrecto, Pandas no puede encontrar la columna y muestra un error.

Por ejemplo, nuestro `DataFrame` tiene una columna llamada `precio`.

Si intentamos escribir:

In [6]:
# Esta celda produce un error porque la columna "Precio" no existe.
# df["Precio"]

Pandas mostrará un error, porque `Precio` con mayúscula inicial no es lo mismo que `precio`.

El error más frecuente en estos casos se llama `KeyError`.

Un `KeyError` significa que intentamos acceder a una clave, etiqueta o nombre que no existe. En este caso, Pandas está diciendo que no encuentra una columna con ese nombre.

También tendríamos un error si escribimos:

In [7]:
# Esta celda produce un error porque la columna se llama "cantidad_vendida".
# df["cantidad vendida"]

porque en nuestro dataset la columna se llama `cantidad_vendida`, con guion bajo.

Para evitar este tipo de errores, conviene revisar los nombres de las columnas antes de seleccionarlas:

In [8]:
df.columns

Index(['producto', 'categoria', 'precio', 'cantidad_vendida', 'sucursal',
       'fecha'],
      dtype='object')

Esta instrucción nos muestra los nombres exactos de las columnas disponibles.

Una buena costumbre es copiar el nombre de la columna tal como aparece en `df.columns`, especialmente cuando el dataset tiene muchas variables o nombres largos.

## Seleccionar una columna como DataFrame

Cuando escribimos:

In [9]:
df["precio"]

0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250
Name: precio, dtype: int64

Pandas devuelve una `Series`.

Una `Series` es una estructura de una sola dimensión. Podemos imaginarla como una columna individual, acompañada por su índice.

Pero a veces queremos seleccionar una sola columna y conservar el formato de tabla, es decir, obtener como resultado un `DataFrame`.

Para eso usamos doble corchete:

In [10]:
df[["precio"]]

   precio
0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250

La diferencia parece pequeña, pero es importante.

Comparemos las dos formas:

```python
df["precio"]
````

devuelve una `Series`.

En cambio:

```python
df[["precio"]]
```

devuelve un `DataFrame` con una sola columna.

Podemos verificarlo usando `type()`.

In [ ]:
type(df["precio"])

 #Salida: pandas.core.series.Series

In [ ]:
type(df[["precio"]])

# Salida: pandas.core.frame.DataFrame

En el primer caso, la salida indica que el objeto es una `Series`.

En el segundo caso, la salida indica que el objeto es un `DataFrame`.

La diferencia entre una `Series` y un `DataFrame` será importante en muchas operaciones de Pandas. Algunas funciones esperan recibir una columna individual, mientras que otras trabajan mejor con una tabla, aunque esa tabla tenga una sola columna.

Por ahora, podemos quedarnos con esta idea:

```text
df["precio"]    → devuelve una Series
df[["precio"]]  → devuelve un DataFrame
```

El doble corchete no es un adorno. Cambia el tipo de objeto que obtenemos como resultado.

## Seleccionar varias columnas

Muchas veces necesitamos trabajar con más de una columna al mismo tiempo.

Por ejemplo, si queremos ver qué producto se vendió y a qué precio, podemos seleccionar las columnas `producto` y `precio`.

Para seleccionar varias columnas, usamos una lista con los nombres de las columnas dentro de los corchetes del `DataFrame`.

In [13]:
df[["producto", "precio"]]

     producto  precio
0    Cuaderno    1200
1    Lapicera     350
2     Mochila    8500
3       Regla     500
4  Cartuchera    3200
5    Cuaderno    1250
6  Marcadores    1800
7     Carpeta     950
8        Goma     300
9       Lapiz     250

En este caso, Pandas devuelve un nuevo `DataFrame` formado solamente por las columnas seleccionadas.

La estructura general es:

```Python
df[["columna_1", "columna_2", "columna_3"]]
```

Es importante observar que usamos doble corchete porque estamos pasando una lista de columnas.

El corchete exterior pertenece a la selección del DataFrame.

El corchete interior pertenece a la lista de nombres de columnas.

Por eso escribimos:

In [15]:
df[["producto", "precio"]]

     producto  precio
0    Cuaderno    1200
1    Lapicera     350
2     Mochila    8500
3       Regla     500
4  Cartuchera    3200
5    Cuaderno    1250
6  Marcadores    1800
7     Carpeta     950
8        Goma     300
9       Lapiz     250

y no:

In [17]:
# Esta celda produce un error porque no se interpreta como una lista de columnas.
# df["producto", "precio"]

La segunda forma produce un error, porque Pandas no interpreta esos dos nombres como una lista de columnas.

Veamos otro ejemplo. Si queremos analizar las ventas por sucursal, podríamos seleccionar:

In [18]:
df[["sucursal", "producto", "cantidad_vendida"]]

  sucursal    producto  cantidad_vendida
0   Centro    Cuaderno                15
1   Centro    Lapicera                40
2    Norte     Mochila                 5
3      Sur       Regla                25
4    Norte  Cartuchera                 8
5      Sur    Cuaderno                12
6   Centro  Marcadores                10
7    Norte     Carpeta                18
8      Sur        Goma                30
9   Centro       Lapiz                50

Esta selección nos permite concentrarnos en tres variables específicas del dataset:

```text
sucursal
producto
cantidad_vendida
```

El `DataFrame` original sigue teniendo todas sus columnas. La selección solo muestra una parte de la tabla.

## Guardar una selección en una nueva variable

Seleccionar columnas no modifica el `DataFrame` original.

Cuando escribimos una selección como:

In [19]:
df[["producto", "precio"]]

     producto  precio
0    Cuaderno    1200
1    Lapicera     350
2     Mochila    8500
3       Regla     500
4  Cartuchera    3200
5    Cuaderno    1250
6  Marcadores    1800
7     Carpeta     950
8        Goma     300
9       Lapiz     250

Pandas nos muestra una tabla con esas columnas, pero `df` sigue conservando todas las columnas originales.

Si queremos reutilizar esa selección más adelante, podemos guardarla en una nueva variable.

In [20]:
productos_y_precios = df[["producto", "precio"]]

productos_y_precios

     producto  precio
0    Cuaderno    1200
1    Lapicera     350
2     Mochila    8500
3       Regla     500
4  Cartuchera    3200
5    Cuaderno    1250
6  Marcadores    1800
7     Carpeta     950
8        Goma     300
9       Lapiz     250

Ahora la variable `productos_y_precios` contiene un nuevo `DataFrame` con solamente dos columnas:

```text
producto
precio
````

Podemos comprobar que el `DataFrame` original sigue igual:

In [21]:
df

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
7     Carpeta    Libreria     950                18    Norte  2024-03-04
8        Goma    Libreria     300                30      Sur  2024-03-05
9       Lapiz    Libreria     250                50   Centro  2024-03-05

Esto es importante porque muchas veces vamos a crear subconjuntos de datos para trabajar de manera más cómoda.

Por ejemplo, podríamos crear un `DataFrame` solamente con las columnas relacionadas con la venta:

In [22]:
datos_venta = df[["producto", "precio", "cantidad_vendida"]]

datos_venta

     producto  precio  cantidad_vendida
0    Cuaderno    1200                15
1    Lapicera     350                40
2     Mochila    8500                 5
3       Regla     500                25
4  Cartuchera    3200                 8
5    Cuaderno    1250                12
6  Marcadores    1800                10
7     Carpeta     950                18
8        Goma     300                30
9       Lapiz     250                50

O podríamos crear otro `DataFrame` con información de ubicación y fecha:

In [23]:
datos_contexto = df[["sucursal", "fecha"]]

datos_contexto

  sucursal       fecha
0   Centro  2024-03-01
1   Centro  2024-03-01
2    Norte  2024-03-02
3      Sur  2024-03-02
4    Norte  2024-03-03
5      Sur  2024-03-03
6   Centro  2024-03-04
7    Norte  2024-03-04
8      Sur  2024-03-05
9   Centro  2024-03-05

Elegir qué columnas conservar depende de la pregunta que queremos responder.

Si queremos analizar importes, seguramente necesitemos `precio` y `cantidad_vendida`.

Si queremos estudiar dónde se registraron las ventas, necesitaremos `sucursal`.

Si queremos analizar la evolución temporal, necesitaremos `fecha`.

Seleccionar columnas es una forma de enfocar el análisis.

## Usar una columna seleccionada

Seleccionar una columna no sirve solamente para verla. También podemos usar esa columna para hacer operaciones.

Por ejemplo, si seleccionamos la columna `precio`, podemos calcular algunos valores simples:

In [24]:
df["precio"].min()

250

In [25]:
df["precio"].max()

8500

In [26]:
df["precio"].mean()

np.float64(1830.0)

Estas instrucciones calculan, respectivamente:

```text
el precio mínimo
el precio máximo
el precio promedio
```

También podemos hacer operaciones con la columna `cantidad_vendida`:

In [27]:
df["cantidad_vendida"].sum()

np.int64(213)

In [28]:
df["cantidad_vendida"].mean()

np.float64(21.3)

En este caso:

```text
sum() calcula la suma total
mean() calcula el promedio
```

Entonces, si escribimos:

In [29]:
df["cantidad_vendida"].sum()

np.int64(213)

estamos pidiendo la cantidad total de productos vendidos en todos los registros del dataset.

Esta forma de trabajo es muy común en Pandas:

```text
seleccionamos una columna
        ↓
aplicamos una operación sobre esa columna
        ↓
interpretamos el resultado
```

Por eso es tan importante aprender a seleccionar columnas correctamente. Muchas operaciones de análisis comienzan eligiendo una o más variables del dataset.

## Seleccionar columnas según la pregunta

Cuando trabajamos con datos, no seleccionamos columnas al azar. Elegimos las columnas que necesitamos según la pregunta que queremos responder.

Por ejemplo, si queremos saber cuáles son los productos más caros, necesitamos mirar la columna `producto` junto con la columna `precio`. En cambio, si queremos saber en qué sucursal se registraron más ventas, nos interesa observar la columna `sucursal`. Si queremos analizar la cantidad de unidades vendidas, necesitamos trabajar con `cantidad_vendida`.

Esta relación entre pregunta y selección es muy importante. Pandas nos da herramientas para seleccionar columnas, pero la decisión de qué columnas seleccionar depende del análisis que queremos hacer.

In [30]:
# Productos y precios

df[["producto", "precio"]]

     producto  precio
0    Cuaderno    1200
1    Lapicera     350
2     Mochila    8500
3       Regla     500
4  Cartuchera    3200
5    Cuaderno    1250
6  Marcadores    1800
7     Carpeta     950
8        Goma     300
9       Lapiz     250

In [31]:
# Sucursales y cantidades vendidas

df[["sucursal", "cantidad_vendida"]]

  sucursal  cantidad_vendida
0   Centro                15
1   Centro                40
2    Norte                 5
3      Sur                25
4    Norte                 8
5      Sur                12
6   Centro                10
7    Norte                18
8      Sur                30
9   Centro                50

In [32]:
# Producto, sucursal y fecha de venta

df[["producto", "sucursal", "fecha"]]

     producto sucursal       fecha
0    Cuaderno   Centro  2024-03-01
1    Lapicera   Centro  2024-03-01
2     Mochila    Norte  2024-03-02
3       Regla      Sur  2024-03-02
4  Cartuchera    Norte  2024-03-03
5    Cuaderno      Sur  2024-03-03
6  Marcadores   Centro  2024-03-04
7     Carpeta    Norte  2024-03-04
8        Goma      Sur  2024-03-05
9       Lapiz   Centro  2024-03-05

En cada caso, seleccionamos una parte diferente del `DataFrame`.

La primera selección nos ayuda a observar los productos junto con sus precios. La segunda permite relacionar cada sucursal con la cantidad vendida. La tercera combina información sobre qué producto se vendió, dónde se vendió y en qué fecha.

En un análisis real, esta decisión se repite constantemente. Primero formulamos una pregunta, luego identificamos qué columnas necesitamos y finalmente aplicamos las operaciones correspondientes.

Una buena forma de pensar el proceso es:

```text
pregunta de análisis → columnas necesarias → operación en Pandas → interpretación
```

Seleccionar columnas es, entonces, una de las primeras formas de transformar una tabla completa en información más enfocada.

## Selección con corchetes y selección con punto

En muchos ejemplos de Pandas es posible que veas otra forma de seleccionar columnas. En lugar de escribir:

In [33]:
df["precio"]

0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250
Name: precio, dtype: int64

a veces se escribe:

In [34]:
df.precio

0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250
Name: precio, dtype: int64

En este caso, ambas instrucciones devuelven la columna `precio`. Sin embargo, en esta serie vamos a preferir la selección con corchetes:

In [ ]:
df["precio"]

Esta forma es más clara y funciona en más situaciones. Por ejemplo, si una columna tiene espacios en su nombre, caracteres especiales, o si su nombre coincide con algún método o atributo de Pandas, la notación con punto puede fallar o generar confusiones.

La notación con corchetes también deja más visible que estamos seleccionando una columna por su nombre. Por eso, aunque `df.precio` pueda funcionar en este caso, conviene acostumbrarse a escribir:

In [35]:
df["precio"]

0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250
Name: precio, dtype: int64

Esta será la forma principal que usaremos para seleccionar columnas.

## Seleccionar columnas como primer recorte del dataset

Cuando seleccionamos columnas, hacemos un primer recorte del dataset. No estamos filtrando filas todavía, ni eliminando datos del `DataFrame` original. Simplemente estamos eligiendo qué variables queremos observar o utilizar.

Esto es útil porque una tabla completa puede contener más información de la que necesitamos en un momento determinado. Si queremos analizar precios, podemos concentrarnos en `producto` y `precio`. Si queremos estudiar las ventas por sucursal, podemos mirar `sucursal` y `cantidad_vendida`. Si queremos trabajar con el momento en que ocurrió cada venta, necesitaremos la columna `fecha`.

En Pandas, este recorte puede producir dos tipos de objetos. Si seleccionamos una sola columna con un corchete, obtenemos una `Series`. Si seleccionamos una o varias columnas usando doble corchete, obtenemos un `DataFrame`.

Podemos resumirlo así:

```text
df["precio"]                  → selecciona una columna como Series

df[["precio"]]                → selecciona una columna como DataFrame

df[["producto", "precio"]]    → selecciona varias columnas como DataFrame
```

Esta diferencia no es solamente visual. Una `Series` y un `DataFrame` son objetos distintos, y algunas operaciones de Pandas se comportan de manera diferente según el tipo de objeto con el que estemos trabajando.

Por ahora, lo más importante es incorporar esta idea: seleccionar columnas nos permite enfocar el análisis en las variables que necesitamos.

## Resumen del capítulo

En este capítulo aprendimos a seleccionar columnas de un `DataFrame`.

Vimos que seleccionar columnas significa quedarnos con una o varias variables del dataset para observarlas, analizarlas o usarlas en operaciones posteriores. Esta es una de las acciones más frecuentes en Pandas, porque muchas veces no necesitamos trabajar con toda la tabla, sino con una parte específica de ella.

Primero seleccionamos una sola columna usando su nombre entre corchetes:

```python
df["precio"]
```

Esa operación devuelve una `Series`, es decir, una estructura de una sola dimensión que conserva los valores de la columna y el índice del `DataFrame`.

Después vimos que también podemos seleccionar una columna como `DataFrame` usando doble corchete:

```python
df[["precio"]]
```

Aunque la diferencia parezca pequeña, el resultado no es el mismo. En el primer caso obtenemos una `Series`; en el segundo, un `DataFrame` con una sola columna.

También aprendimos a seleccionar varias columnas al mismo tiempo:

```python
df[["producto", "precio"]]
```

En ese caso, Pandas devuelve un nuevo `DataFrame` formado solo por las columnas seleccionadas.

A lo largo del capítulo también vimos que los nombres de columnas deben escribirse exactamente como aparecen en el `DataFrame`. Pandas distingue entre mayúsculas y minúsculas, espacios, guiones bajos y otros caracteres. Por eso, cuando tenemos dudas, conviene revisar los nombres disponibles con:

```python
df.columns
```

Finalmente, vimos que seleccionar columnas no modifica el `DataFrame` original. Si queremos reutilizar una selección, podemos guardarla en una nueva variable.

La idea principal de este capítulo fue:

```text
Seleccionar columnas nos permite enfocar el análisis en las variables que necesitamos.
```

Esta operación será la base para muchas tareas posteriores: calcular resúmenes, comparar variables, construir nuevos datasets, aplicar filtros y preparar datos para visualizaciones.

## Próximo paso

Ya sabemos seleccionar columnas, es decir, elegir variables específicas de un `DataFrame`.

El siguiente paso será aprender a seleccionar filas. Esto nos permitirá observar registros particulares, trabajar con posiciones dentro de la tabla y empezar a preparar el camino para los filtros condicionales.

Más adelante vamos a combinar ambas ideas: seleccionar columnas y seleccionar filas al mismo tiempo. Esa combinación nos dará mucho más control sobre qué parte del dataset queremos analizar.