<a href="https://colab.research.google.com/github/VintaBytes/Ciencia-de-datos/blob/main/CienciaDeDatosConPython/CuadernosColab/CienciaDeDatos_Cap%C3%ADtulo002_Primeras_inspecciones_de_un_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Abrir en Colab"/></a>

# Capítulo 2 — Primeras inspecciones de un DataFrame

## Breve repaso

En el capítulo anterior comenzamos a construir una base conceptual para el trabajo con datos.

Vimos que un dataset es un conjunto organizado de datos y que, muchas veces, se presenta en forma de tabla. También reconocimos sus partes principales: filas, columnas, observaciones, variables y valores.

Además, hicimos un primer contacto con Pandas y construimos un `DataFrame` sencillo. Ese primer ejemplo nos permitió ver que Pandas puede representar datos tabulares dentro de Python y ayudarnos a responder preguntas simples.

En este capítulo vamos a dar un paso más.

Ya no nos vamos a conformar con “mirar” una tabla. Vamos a aprender a inspeccionar un `DataFrame` de manera más ordenada, revisando sus primeras filas, sus últimas filas, sus dimensiones, sus columnas, su índice, sus tipos de datos y algunas estadísticas iniciales.

Antes de limpiar, transformar, resumir o visualizar datos, necesitamos saber con qué estamos trabajando. Por eso, la inspección inicial es una etapa fundamental en cualquier análisis de datos.

Al finalizar este capítulo deberías poder:

- Mostrar las primeras y últimas filas de un `DataFrame`.
- Conocer cuántas filas y columnas tiene un dataset.
- Revisar los nombres de las columnas.
- Reconocer el índice de un `DataFrame`.
- Consultar los tipos de datos de cada columna.
- Obtener información general con `info()`.
- Calcular estadísticas iniciales con `describe()`.
- Formular primeras observaciones sobre la estructura de un dataset.

## Por qué inspeccionar un DataFrame

Cuando recibimos un dataset, puede ser tentador empezar directamente a calcular promedios, crear gráficos o buscar conclusiones.

Sin embargo, antes de analizar los datos necesitamos conocer su estructura.

Inspeccionar un `DataFrame` significa hacer una primera revisión para responder preguntas como estas:

```text
¿Cuántas filas tiene?
¿Cuántas columnas tiene?
¿Qué representa cada columna?
¿Cómo se llaman las columnas?
¿Qué tipos de datos contiene?
¿Hay columnas numéricas?
¿Hay columnas categóricas?
¿Aparecen valores faltantes?
¿Los datos parecen estar cargados correctamente?
```

Esta revisión inicial nos ayuda a evitar errores.

Por ejemplo, si una columna de precios fue cargada como texto, Pandas podría no permitirnos calcular correctamente un promedio. Si una columna tiene muchos valores faltantes, tal vez necesitemos tratar ese problema antes de analizarla. Si los nombres de las columnas son confusos, puede ser difícil escribir código claro.

La inspección inicial no resuelve todos los problemas del dataset, pero nos permite construir un primer diagnóstico.

Podemos pensarla como una lectura exploratoria:

```text
antes de transformar los datos,
primero necesitamos conocerlos.
```

En este capítulo vamos a aprender algunas herramientas básicas de Pandas para realizar esa primera revisión.

## Dataset de trabajo

Para practicar las primeras herramientas de inspección, vamos a crear un dataset pequeño relacionado con ventas de una librería.

Cada fila representará la venta de un producto. Cada columna describirá una característica de esa venta: el producto vendido, la categoría, el precio unitario, la cantidad vendida, la sucursal y la fecha.

Este dataset todavía será simple, pero nos permitirá revisar varios elementos importantes de un `DataFrame`: filas, columnas, índice, tipos de datos y estadísticas iniciales.

In [1]:
import pandas as pd

datos = {
    "producto": [
        "Cuaderno", "Lapicera", "Mochila", "Regla", "Cartuchera",
        "Cuaderno", "Marcadores", "Carpeta", "Goma", "Lapiz"
    ],
    "categoria": [
        "Libreria", "Libreria", "Accesorios", "Libreria", "Accesorios",
        "Libreria", "Libreria", "Libreria", "Libreria", "Libreria"
    ],
    "precio": [
        1200, 350, 8500, 500, 3200,
        1250, 1800, 950, 300, 250
    ],
    "cantidad_vendida": [
        15, 40, 5, 25, 8,
        12, 10, 18, 30, 50
    ],
    "sucursal": [
        "Centro", "Centro", "Norte", "Sur", "Norte",
        "Sur", "Centro", "Norte", "Sur", "Centro"
    ],
    "fecha": [
        "2024-03-01", "2024-03-01", "2024-03-02", "2024-03-02", "2024-03-03",
        "2024-03-03", "2024-03-04", "2024-03-04", "2024-03-05", "2024-03-05"
    ]
}

df = pd.DataFrame(datos)

df

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
7     Carpeta    Libreria     950                18    Norte  2024-03-04
8        Goma    Libreria     300                30      Sur  2024-03-05
9       Lapiz    Libreria     250                50   Centro  2024-03-05

## Ver las primeras filas con `head()`

Cuando un dataset tiene muchas filas, no siempre conviene mostrarlo completo. En esos casos, una de las primeras acciones que solemos realizar es mirar solo las primeras filas.

Para eso Pandas ofrece el método `head()`.

Este método nos permite obtener una vista rápida del comienzo del `DataFrame`.

In [2]:
df.head()

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03

Por defecto, `head()` muestra las primeras cinco filas del `DataFrame`.

Esto resulta útil para revisar rápidamente:

- si el dataset se cargó correctamente;
- si las columnas aparecen con los nombres esperados;
- si los valores tienen una forma razonable;
- si la tabla parece representar lo que esperábamos.

En nuestro caso, al usar `df.head()` vemos las primeras ventas registradas en el dataset.

También podemos indicar cuántas filas queremos ver. Por ejemplo, si queremos observar solo las primeras tres filas, podemos escribir:

In [3]:
df.head(3)

   producto   categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno    Libreria    1200                15   Centro  2024-03-01
1  Lapicera    Libreria     350                40   Centro  2024-03-01
2   Mochila  Accesorios    8500                 5    Norte  2024-03-02

El número entre paréntesis indica cuántas filas queremos mostrar.

Entonces:

```python
df.head(3)
```

significa:

```text
mostrá las primeras 3 filas del DataFrame df
```

Esta instrucción no modifica el dataset. Solamente muestra una parte de la tabla para que podamos inspeccionarla.

## Ver las últimas filas con `tail()`

Así como `head()` permite ver las primeras filas de un `DataFrame`, Pandas también ofrece el método `tail()`, que permite ver las últimas filas.

Esto es útil porque, a veces, los problemas de un dataset no aparecen al principio. Puede ocurrir que las primeras filas estén bien cargadas, pero que al final haya datos incompletos, totales agregados, notas aclaratorias o registros con otro formato.

Para revisar el final del `DataFrame`, usamos:

In [4]:
df.tail()

     producto categoria  precio  cantidad_vendida sucursal       fecha
5    Cuaderno  Libreria    1250                12      Sur  2024-03-03
6  Marcadores  Libreria    1800                10   Centro  2024-03-04
7     Carpeta  Libreria     950                18    Norte  2024-03-04
8        Goma  Libreria     300                30      Sur  2024-03-05
9       Lapiz  Libreria     250                50   Centro  2024-03-05

Por defecto, `tail()` muestra las últimas cinco filas.

En nuestro dataset, esto nos permite observar las ventas registradas hacia el final de la tabla.

También podemos indicar cuántas filas queremos ver. Por ejemplo:

In [5]:
df.tail(3)

  producto categoria  precio  cantidad_vendida sucursal       fecha
7  Carpeta  Libreria     950                18    Norte  2024-03-04
8     Goma  Libreria     300                30      Sur  2024-03-05
9    Lapiz  Libreria     250                50   Centro  2024-03-05

En este caso, Pandas muestra las últimas tres filas del `DataFrame`.

Podemos pensar estas dos herramientas como una primera mirada rápida:

```text
head() → muestra el comienzo del DataFrame
tail() → muestra el final del DataFrame
```

Ninguna de estas instrucciones modifica los datos. Solo nos ayudan a inspeccionarlos.

## Conocer las dimensiones con `shape`

Después de mirar las primeras y las últimas filas, una pregunta muy común es:

```text
¿Cuántas filas y cuántas columnas tiene este dataset?
```

En Pandas podemos responder esa pregunta usando `shape`.

A diferencia de `head()` y `tail()`, `shape` no se escribe con paréntesis porque no es un método, sino un atributo del `DataFrame`.


```python
df.shape
```

La salida de `df.shape` tiene dos valores:

```text
(filas, columnas)
```

En nuestro caso, el resultado es:

```text
(10, 6)
```

Esto significa que el `DataFrame` tiene 10 filas y 6 columnas.

También podemos guardar esos dos valores en variables separadas:


```python
cantidad_filas, cantidad_columnas = df.shape

cantidad_filas
cantidad_columnas
```


Esto puede ser útil cuando queremos usar esos valores más adelante en un análisis o en un mensaje.

Por ejemplo:

```python
print(f"El dataset tiene {cantidad_filas} filas y {cantidad_columnas} columnas.")
```

Conocer las dimensiones del dataset es una de las primeras tareas de inspección.

Un dataset con 10 filas puede revisarse casi completo a simple vista. Pero uno con 10.000, 100.000 o varios millones de filas necesita herramientas de inspección, resumen y filtrado.

Por eso, `shape` nos da una primera idea del tamaño del problema con el que estamos trabajando.

## Revisar los nombres de las columnas

Después de conocer las dimensiones del `DataFrame`, conviene revisar cómo se llaman sus columnas.

Los nombres de columnas son importantes porque los usamos para seleccionar datos, hacer cálculos, aplicar filtros y construir nuevas variables.

En Pandas podemos consultar los nombres de las columnas usando el atributo `columns`.

In [6]:
df.columns

Index(['producto', 'categoria', 'precio', 'cantidad_vendida', 'sucursal',
       'fecha'],
      dtype='object')

La salida muestra los nombres de todas las columnas del `DataFrame`.

En nuestro dataset aparecen estas columnas:

```text
producto
categoria
precio
cantidad_vendida
sucursal
fecha
```

Estos nombres nos dicen qué información contiene cada variable.

También podemos convertir los nombres de columnas en una lista de Python, si queremos verlos de una manera más simple:

In [7]:
list(df.columns)

['producto', 'categoria', 'precio', 'cantidad_vendida', 'sucursal', 'fecha']

Esto devuelve una lista con los nombres de las columnas.

Revisar los nombres de columnas es una tarea sencilla, pero muy importante. En datasets reales podemos encontrar problemas como:

```text
nombres demasiado largos
nombres poco claros
espacios al principio o al final
mayúsculas y minúsculas mezcladas
caracteres especiales
columnas sin nombre
```

Por ejemplo, una columna llamada `precio` es clara. En cambio, una columna llamada `columna_3`, `dato1` o `valor_final_2` puede dificultar la interpretación.

Más adelante vamos a aprender a limpiar y modificar nombres de columnas. Por ahora, nos interesa incorporar esta costumbre: antes de analizar un dataset, conviene revisar cómo están nombradas sus variables.

## Reconocer el índice del DataFrame

Además de filas y columnas, un `DataFrame` tiene un elemento muy importante: el **índice**.

El índice sirve para identificar las filas. En muchos casos, Pandas crea automáticamente un índice numérico que empieza en `0`.

Cuando mostramos nuestro dataset, vemos a la izquierda una serie de números:

```text
0
1
2
3
4
...
```

Esos números no pertenecen a ninguna de las columnas originales del dataset. Son el índice que Pandas asignó a cada fila.

Podemos consultar el índice usando el atributo `index`.

In [8]:
df.index

RangeIndex(start=0, stop=10, step=1)

La salida indica cómo está construido el índice.

En este caso, Pandas nos muestra algo parecido a:

```text
RangeIndex(start=0, stop=10, step=1)
```

Esto significa que el índice:

```text
empieza en 0
termina antes de 10
avanza de 1 en 1
```

Como nuestro dataset tiene 10 filas, los índices van desde `0` hasta `9`.

Es importante recordar que el índice no siempre coincide con una columna del dataset. En este ejemplo, el índice fue creado automáticamente por Pandas.

Más adelante vamos a trabajar con el índice con más detalle. Veremos cómo cambiarlo, cómo resetearlo y cómo usarlo para seleccionar filas. Por ahora, nos alcanza con reconocer que el índice identifica las filas del `DataFrame`.

## Revisar los tipos de datos

Además de conocer las filas, las columnas y el índice, también necesitamos revisar qué tipo de dato tiene cada columna.

En Pandas, cada columna tiene un tipo de dato asociado. Ese tipo de dato le indica a Pandas cómo debe interpretar los valores de esa columna.

Por ejemplo, una columna puede contener:

```text
números enteros
números decimales
textos
fechas
valores booleanos
```

Podemos consultar los tipos de datos usando `dtypes`.

In [9]:
df.dtypes

producto            object
categoria           object
precio               int64
cantidad_vendida     int64
sucursal            object
fecha               object
dtype: object

La salida muestra cada columna junto con el tipo de dato que Pandas le asignó.

En nuestro dataset podríamos ver algo similar a esto:

```text
producto            object
categoria           object
precio               int64
cantidad_vendida     int64
sucursal            object
fecha               object
dtype: object
```

Las columnas `precio` y `cantidad_vendida` aparecen como `int64`, porque contienen números enteros.

En cambio, las columnas `producto`, `categoria`, `sucursal` y `fecha` aparecen como `object`.

En Pandas, el tipo `object` suele usarse para columnas que contienen texto. Por eso es esperable que `producto`, `categoria` y `sucursal` aparezcan de esa manera.

Pero hay un detalle interesante: la columna `fecha` también aparece como `object`.

Eso ocurre porque, por ahora, las fechas fueron cargadas como texto. Pandas no las está interpretando todavía como fechas reales.

Esto no es un error grave en este momento, pero es una observación importante. Si más adelante queremos ordenar, filtrar o agrupar por fechas, probablemente necesitemos convertir esa columna a un tipo de dato temporal.

Este es un buen ejemplo de por qué conviene revisar los tipos de datos al inicio. A simple vista, una columna puede parecer una fecha, un número o una categoría, pero Pandas puede haberla interpretado de otra manera.

## Obtener información general con `info()`

Pandas ofrece un método muy útil para obtener un resumen general del `DataFrame`: `info()`.

Este método muestra información sobre:

```text
cantidad de filas
cantidad de columnas
nombre de cada columna
cantidad de valores no nulos
tipo de dato de cada columna
uso aproximado de memoria
```

Lo usamos así:

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   producto          10 non-null     object
 1   categoria         10 non-null     object
 2   precio            10 non-null     int64
 3   cantidad_vendida  10 non-null     int64
 4   sucursal          10 non-null     object
 5   fecha             10 non-null     object
dtypes: int64(2), object(4)
memory usage: 612.0+ bytes

La salida de `info()` puede parecer un poco más técnica al principio, pero contiene información muy importante.

En nuestro dataset, deberíamos observar que hay 10 entradas, es decir, 10 filas. También deberíamos ver las 6 columnas:

```text
producto
categoria
precio
cantidad_vendida
sucursal
fecha
```

La columna `Non-Null Count` indica cuántos valores no nulos tiene cada columna.

Si una columna tiene 10 valores no nulos y el dataset tiene 10 filas, significa que esa columna no tiene valores faltantes.

Por ejemplo:

```text
10 non-null
```

significa que hay 10 valores cargados en esa columna.

Si en una columna apareciera algo como:

```text
8 non-null
```

eso indicaría que, de las 10 filas, solo 8 tienen un valor cargado en esa columna. Las otras 2 filas tendrían valores faltantes.

También vemos el tipo de dato de cada columna, igual que cuando usamos `dtypes`.

Por eso, `info()` suele ser una de las primeras instrucciones que usamos al recibir un dataset nuevo. Nos permite obtener rápidamente una primera imagen de su estructura y de posibles problemas.

## Obtener estadísticas iniciales con `describe()`

Además de revisar la estructura del `DataFrame`, muchas veces queremos obtener un primer resumen estadístico de sus columnas numéricas.

Para eso podemos usar el método `describe()`.

Este método calcula automáticamente algunas medidas descriptivas básicas.

In [11]:
df.describe()

            precio  cantidad_vendida
count    10.000000          10.00000
mean   1830.000000          21.30000
std    2509.338115          14.79527
min     250.000000           5.00000
25%     387.500000          10.50000
50%    1075.000000          16.50000
75%    1662.500000          28.75000
max    8500.000000          50.00000

En nuestro dataset, `describe()` analiza las columnas numéricas:

```text
precio
cantidad_vendida
````

La salida incluye varias filas:

| Medida  | Significado                   |
| ------- | ----------------------------- |
| `count` | Cantidad de valores no nulos. |
| `mean`  | Promedio.                     |
| `std`   | Desvío estándar.              |
| `min`   | Valor mínimo.                 |
| `25%`   | Primer cuartil.               |
| `50%`   | Mediana.                      |
| `75%`   | Tercer cuartil.               |
| `max`   | Valor máximo.                 |

No necesitamos interpretar todas estas medidas en profundidad todavía. Más adelante vamos a estudiar estadística descriptiva con más detalle.

Por ahora, lo importante es comprender que `describe()` nos ofrece una primera mirada general sobre las columnas numéricas.

Por ejemplo, podemos observar cuál es el precio mínimo, cuál es el precio máximo, cuál es el promedio de precios y cuántos valores hay cargados.

También podemos usar `describe()` sobre una sola columna:

In [12]:
df["precio"].describe()

count      10.000000
mean     1830.000000
std      2509.338115
min       250.000000
25%       387.500000
50%      1075.000000
75%      1662.500000
max      8500.000000
Name: precio, dtype: float64

En este caso, Pandas calcula el resumen estadístico solamente para la columna `precio`.

Esta herramienta es útil para empezar a detectar valores llamativos. Por ejemplo, si el precio mínimo fuera negativo o si el precio máximo fuera exageradamente alto, eso podría indicar un posible problema en los datos.

`describe()` no reemplaza una revisión cuidadosa, pero ayuda a construir una primera impresión del dataset.

## Describir columnas no numéricas

Cuando usamos `df.describe()`, Pandas resume automáticamente las columnas numéricas.

Pero un dataset también puede tener columnas no numéricas, como `producto`, `categoria` o `sucursal`.

Si queremos obtener un resumen de todas las columnas, podemos usar `include="all"`.

In [13]:
df.describe(include="all")

        producto categoria       precio  cantidad_vendida sucursal       fecha
count         10        10    10.000000          10.00000       10          10
unique         9         2          NaN               NaN        3           5
top     Cuaderno  Libreria          NaN               NaN   Centro  2024-03-01
freq           2         8          NaN               NaN        4           2
mean         NaN       NaN  1830.000000          21.30000      NaN         NaN
std          NaN       NaN  2509.338115          14.79527      NaN         NaN
min          NaN       NaN   250.000000           5.00000      NaN         NaN
25%          NaN       NaN   387.500000          10.50000      NaN         NaN
50%          NaN       NaN  1075.000000          16.50000      NaN         NaN
75%          NaN       NaN  1662.500000          28.75000      NaN         NaN
max          NaN       NaN  8500.000000          50.00000      NaN         NaN

La salida ahora incluye también columnas de texto.

Para las columnas no numéricas, Pandas muestra otras medidas:

| Medida | Significado |
|---|---|
| `count` | Cantidad de valores no nulos. |
| `unique` | Cantidad de valores distintos. |
| `top` | Valor que aparece con mayor frecuencia. |
| `freq` | Frecuencia del valor más repetido. |

Por ejemplo, en la columna `sucursal`, `unique` nos indica cuántas sucursales diferentes aparecen en el dataset.

En la columna `producto`, `top` indica cuál es el producto que aparece más veces, y `freq` indica cuántas veces aparece.

Este tipo de resumen puede ser útil para comenzar a entender columnas categóricas o de texto.

Sin embargo, también debemos leerlo con cuidado. En columnas como `producto`, que pueden tener muchos valores distintos, a veces conviene usar otras herramientas, como `value_counts()`, para ver con más detalle la frecuencia de cada valor.

Y podemos agregar una primera comparación con `value_counts()`:

In [14]:
df["sucursal"].value_counts()

sucursal
Centro    4
Norte     3
Sur       3
Name: count, dtype: int64

Esta instrucción cuenta cuántas veces aparece cada sucursal.

A diferencia de `describe(include="all")`, que nos da un resumen general, `value_counts()` nos muestra directamente la frecuencia de cada categoría.

En este caso, nos permite responder una pregunta simple:

```text
¿Cuántas ventas se registraron en cada sucursal?
```

## Construir una primera lectura del dataset

Hasta ahora usamos varias herramientas de inspección:

```text
head()
tail()
shape
columns
index
dtypes
info()
describe()
value_counts()
```

Cada una responde una pregunta distinta sobre el `DataFrame`.

Podemos organizar esas herramientas de esta manera:

| Pregunta                                                | Herramienta posible |
| ------------------------------------------------------- | ------------------- |
| ¿Cómo son las primeras filas?                           | `head()`            |
| ¿Cómo son las últimas filas?                            | `tail()`            |
| ¿Cuántas filas y columnas tiene?                        | `shape`             |
| ¿Cómo se llaman las columnas?                           | `columns`           |
| ¿Cómo está identificado cada registro?                  | `index`             |
| ¿Qué tipo de dato tiene cada columna?                   | `dtypes`            |
| ¿Hay valores faltantes visibles en el resumen?          | `info()`            |
| ¿Qué resumen estadístico tienen las columnas numéricas? | `describe()`        |
| ¿Cuántas veces aparece cada categoría?                  | `value_counts()`    |

Estas herramientas no reemplazan el análisis profundo, pero nos permiten construir una primera lectura del dataset.

Por ejemplo, a partir de lo que vimos podemos decir:

```text
El dataset tiene 10 filas y 6 columnas.
Cada fila representa una venta.
Las columnas incluyen producto, categoria, precio, cantidad vendida, sucursal y fecha.
Las columnas precio y cantidad_vendida son numéricas.
La columna fecha parece una fecha, pero Pandas la interpreta todavía como texto.
No se observan valores faltantes en este dataset.
```

Este tipo de lectura inicial es muy importante. Antes de limpiar, transformar, agrupar o visualizar datos, necesitamos saber qué tenemos delante.

Una buena práctica es no empezar directamente por los cálculos, sino dedicar unos minutos a revisar la estructura del dataset.

## Resumen del capítulo

En este capítulo aprendimos a realizar una primera inspección de un `DataFrame`.

La inspección inicial es una etapa fundamental del trabajo con datos. Antes de limpiar, transformar, analizar o visualizar un dataset, necesitamos conocer su estructura general.

Para eso trabajamos con varias herramientas básicas de Pandas:

```text
head()
tail()
shape
columns
index
dtypes
info()
describe()
value_counts()
```

Vimos que `head()` y `tail()` permiten observar el comienzo y el final del `DataFrame`, sin necesidad de mostrarlo completo.

También usamos `shape` para conocer la cantidad de filas y columnas, `columns` para revisar los nombres de las variables, e `index` para reconocer cómo Pandas identifica las filas.

Luego revisamos los tipos de datos con `dtypes`. Esta inspección nos permitió observar que algunas columnas fueron interpretadas como números enteros, mientras que otras fueron interpretadas como texto. En particular, vimos que la columna `fecha` parecía contener fechas, pero Pandas todavía la interpretaba como `object`.

Después usamos `info()` para obtener una vista general del dataset, incluyendo cantidad de columnas, cantidad de valores no nulos y tipos de datos.

Finalmente, usamos `describe()` para obtener estadísticas iniciales de las columnas numéricas, y `describe(include="all")` junto con `value_counts()` para observar también columnas categóricas o de texto.

La idea principal de este capítulo fue:

```text
Antes de analizar un dataset, primero necesitamos inspeccionarlo.
```

Una buena inspección inicial nos ayuda a entender qué datos tenemos, detectar posibles problemas y decidir qué pasos conviene seguir.

## Próximo paso

Ahora que sabemos inspeccionar la estructura general de un `DataFrame`, estamos en condiciones de empezar a trabajar con partes específicas del dataset.

Más adelante vamos a aprender a seleccionar columnas, seleccionar filas y construir subconjuntos de datos. Esto nos permitirá responder preguntas más precisas y preparar el camino para filtros, limpieza y análisis más detallados.