# Capítulo 5 — Selección con etiquetas usando loc

## Breve repaso

En el capítulo anterior aprendimos a seleccionar filas de un `DataFrame` usando `iloc`.

Vimos que `iloc` trabaja con posiciones numéricas. Por ejemplo, `df.iloc[0]` selecciona la primera fila, `df.iloc[1]` selecciona la segunda, y `df.iloc[0:3]` selecciona las filas ubicadas desde la posición `0` hasta antes de la posición `3`.

También vimos que `iloc` puede combinar filas y columnas usando posiciones, como en `df.iloc[0:4, [0, 2, 3]]`. Esa instrucción permite seleccionar un conjunto de filas y columnas indicando su ubicación dentro del `DataFrame`.

En este capítulo vamos a trabajar con otra herramienta fundamental de Pandas: `loc`.

A diferencia de `iloc`, que selecciona por posición, `loc` selecciona usando etiquetas. Esto significa que podemos indicar nombres de columnas y etiquetas del índice. En muchos casos, esta forma de selección resulta más clara porque permite escribir directamente qué columnas queremos observar.

Por ejemplo, en lugar de seleccionar la columna ubicada en la posición `2`, podemos seleccionar la columna llamada `"precio"`.

A lo largo del capítulo vamos a ver cómo usar `loc` para seleccionar filas, columnas y combinaciones de filas y columnas. También vamos a reforzar una idea importante: posición e índice pueden parecer lo mismo en algunos datasets, pero no siempre lo son.

Al finalizar este capítulo deberías poder:

- Comprender la diferencia entre `iloc` y `loc`.
- Seleccionar filas usando etiquetas del índice.
- Seleccionar columnas usando sus nombres.
- Combinar selección de filas y columnas con `loc`.
- Reconocer cuándo una selección devuelve una `Series` y cuándo devuelve un `DataFrame`.
- Entender por qué `loc` suele mejorar la legibilidad del código cuando trabajamos con nombres de columnas.

## Dataset de trabajo

En este capítulo vamos a seguir usando el dataset de ventas de una librería.

Ya conocemos sus columnas principales: `producto`, `categoria`, `precio`, `cantidad_vendida`, `sucursal` y `fecha`. También sabemos que cada fila representa una venta registrada. Usar el mismo dataset nos permite concentrarnos en el nuevo tema: la selección con etiquetas usando `loc`.

Primero vamos a crear nuevamente el `DataFrame`.

In [1]:
import pandas as pd

datos = {
    "producto": [
        "Cuaderno", "Lapicera", "Mochila", "Regla", "Cartuchera",
        "Cuaderno", "Marcadores", "Carpeta", "Goma", "Lapiz"
    ],
    "categoria": [
        "Libreria", "Libreria", "Accesorios", "Libreria", "Accesorios",
        "Libreria", "Libreria", "Libreria", "Libreria", "Libreria"
    ],
    "precio": [
        1200, 350, 8500, 500, 3200,
        1250, 1800, 950, 300, 250
    ],
    "cantidad_vendida": [
        15, 40, 5, 25, 8,
        12, 10, 18, 30, 50
    ],
    "sucursal": [
        "Centro", "Centro", "Norte", "Sur", "Norte",
        "Sur", "Centro", "Norte", "Sur", "Centro"
    ],
    "fecha": [
        "2024-03-01", "2024-03-01", "2024-03-02", "2024-03-02", "2024-03-03",
        "2024-03-03", "2024-03-04", "2024-03-04", "2024-03-05", "2024-03-05"
    ]
}

df = pd.DataFrame(datos)

df

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
7     Carpeta    Libreria     950                18    Norte  2024-03-04
8        Goma    Libreria     300                30      Sur  2024-03-05
9       Lapiz    Libreria     250                50   Centro  2024-03-05

Como el índice fue creado automáticamente por Pandas, las filas aparecen identificadas con etiquetas numéricas desde `0` hasta `9`.

En este caso, esas etiquetas coinciden visualmente con las posiciones de las filas. Sin embargo, durante el capítulo vamos a ver que `loc` e `iloc` no funcionan de la misma manera. `iloc` usa posiciones; `loc` usa etiquetas.

## Diferencia entre iloc y loc

En Pandas existen varias formas de seleccionar datos. Dos de las más importantes son `iloc` y `loc`.

La diferencia central es esta:

```text
iloc selecciona por posición.
loc selecciona por etiqueta.
```

Cuando usamos `iloc`, indicamos posiciones numéricas. Por ejemplo, la posición `0`, la posición `1` o el rango `0:3`.

Cuando usamos `loc`, indicamos etiquetas. Esas etiquetas pueden ser los valores del índice para seleccionar filas, o los nombres de las columnas para seleccionar variables.

En nuestro `DataFrame` actual, el índice es numérico y va de `0` a `9`. Por eso, al principio puede parecer que `loc` e `iloc` hacen lo mismo. Sin embargo, conceptualmente trabajan de manera distinta.

Por ejemplo:

```python
df.iloc[0]
```

selecciona la fila que está en la primera posición.

En cambio:

```python
df.loc[0]
```

selecciona la fila cuya etiqueta de índice es `0`.

En este dataset, ambas instrucciones devuelven la misma fila porque el índice coincide con las posiciones. Pero esto no siempre será así. Si el índice estuviera formado por códigos, fechas o nombres, `loc` usaría esas etiquetas, no la posición física de la fila.

Esta diferencia será cada vez más importante a medida que trabajemos con datasets más complejos.

In [2]:
df.iloc[0]

producto              Cuaderno
categoria             Libreria
precio                    1200
cantidad_vendida            15
sucursal                Centro
fecha               2024-03-01
Name: 0, dtype: object

In [3]:
df.loc[0]

producto              Cuaderno
categoria             Libreria
precio                    1200
cantidad_vendida            15
sucursal                Centro
fecha               2024-03-01
Name: 0, dtype: object

En este caso, las dos salidas son iguales porque el índice del `DataFrame` coincide con las posiciones. Aun así, conviene recordar la diferencia conceptual: `iloc` responde a la pregunta “¿qué fila está en esta posición?”, mientras que `loc` responde a la pregunta “¿qué fila tiene esta etiqueta?”.

## Seleccionar filas con loc

`loc` permite seleccionar filas usando las etiquetas del índice.

En nuestro `DataFrame`, el índice fue creado automáticamente por Pandas y está formado por los números del `0` al `9`. Por eso, podemos seleccionar la fila cuya etiqueta es `0` escribiendo:

In [4]:
df.loc[0]

producto              Cuaderno
categoria             Libreria
precio                    1200
cantidad_vendida            15
sucursal                Centro
fecha               2024-03-01
Name: 0, dtype: object

La salida muestra la fila identificada con la etiqueta `0`.

En este caso, esa fila también es la primera fila del `DataFrame`, pero eso ocurre porque el índice automático coincide con las posiciones. Lo importante es recordar que `loc[0]` no significa necesariamente “primera fila”, sino “fila cuya etiqueta de índice es `0`”.

También podemos seleccionar otra fila por su etiqueta:

In [5]:
df.loc[3]

producto                 Regla
categoria             Libreria
precio                     500
cantidad_vendida            25
sucursal                   Sur
fecha               2024-03-02
Name: 3, dtype: object

Esta instrucción selecciona la fila cuya etiqueta de índice es `3`.

Como el índice actual es simple y numérico, el resultado parece muy parecido al que obtendríamos con `iloc`. Sin embargo, la lógica no es la misma:


```text
df.iloc[3] → selecciona la fila ubicada en la posición 3

df.loc[3]  → selecciona la fila cuya etiqueta de índice es 3
```

En este dataset ambas instrucciones devuelven la misma fila, pero más adelante veremos ejemplos donde esto no ocurre.

## Seleccionar varias filas con loc

También podemos usar `loc` para seleccionar varias filas. Si queremos seleccionar varias etiquetas puntuales del índice, podemos pasar una lista de etiquetas:

In [6]:
df.loc[[0, 3, 5]]

   producto categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno  Libreria    1200                15   Centro  2024-03-01
3     Regla  Libreria     500                25      Sur  2024-03-02
5  Cuaderno  Libreria    1250                12      Sur  2024-03-03

En este caso, Pandas devuelve las filas cuyas etiquetas de índice son `0`, `3` y `5`. Como estamos seleccionando varias filas, el resultado es un `DataFrame`.

También podemos seleccionar un rango de etiquetas:

In [7]:
df.loc[0:3]

   producto   categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno    Libreria    1200                15   Centro  2024-03-01
1  Lapicera    Libreria     350                40   Centro  2024-03-01
2   Mochila  Accesorios    8500                 5    Norte  2024-03-02
3     Regla    Libreria     500                25      Sur  2024-03-02

Esta instrucción selecciona las filas cuyas etiquetas van desde `0` hasta `3`. Acá aparece una diferencia importante entre `loc` e `iloc`.

Con `iloc`, el final del rango no se incluye:

```python
df.iloc[0:3]
```

selecciona las posiciones `0`, `1` y `2`. En cambio, con `loc`, cuando usamos etiquetas, el final del rango sí se incluye:

```python
df.loc[0:3]
```

selecciona las etiquetas `0`, `1`, `2` y `3`. Esta diferencia puede parecer pequeña, pero es muy importante para evitar errores al seleccionar datos.

Podemos resumirlo así:

```text
df.iloc[0:3] → selecciona posiciones 0, 1 y 2

df.loc[0:3]  → selecciona etiquetas 0, 1, 2 y 3
```

En nuestro dataset actual, como el índice coincide con las posiciones, esta diferencia se nota claramente en la cantidad de filas seleccionadas.

## Seleccionar columnas con loc

Aunque `loc` suele presentarse como una herramienta para seleccionar por etiquetas del índice, también permite seleccionar columnas usando sus nombres.

La estructura general de `loc` es:

```python
df.loc[filas, columnas]
```

El primer lugar corresponde a las filas y el segundo a las columnas.

Si queremos seleccionar todas las filas, usamos `:` en la parte de las filas. Luego, en la parte de columnas, indicamos el nombre de la columna que queremos seleccionar.

In [8]:
df.loc[:, "precio"]

0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250
Name: precio, dtype: int64

In [9]:
df.loc[:, ["precio"]]

   precio
0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250

En este caso, el resultado conserva el formato de tabla.

La diferencia es similar a la que vimos antes:

```text
df.loc[:, "precio"]    → devuelve una Series

df.loc[:, ["precio"]]  → devuelve un DataFrame
```

Usar `loc` de esta manera puede parecer más largo que escribir simplemente `df["precio"]`, pero tiene una ventaja: permite combinar en una misma instrucción qué filas y qué columnas queremos seleccionar.

## Seleccionar varias columnas con loc

Con `loc` también podemos seleccionar varias columnas por nombre. Para hacerlo, indicamos todas las filas con `:` y luego pasamos una lista con los nombres de las columnas que queremos conservar.

In [10]:
df.loc[:, ["producto", "precio"]]

     producto  precio
0    Cuaderno    1200
1    Lapicera     350
2     Mochila    8500
3       Regla     500
4  Cartuchera    3200
5    Cuaderno    1250
6  Marcadores    1800
7     Carpeta     950
8        Goma     300
9       Lapiz     250

Esta instrucción selecciona todas las filas del `DataFrame`, pero solamente las columnas `producto` y `precio`.

Podemos leerla de esta manera:

```text
de todas las filas,
mostrar solamente producto y precio
```

También podemos seleccionar otras combinaciones de columnas según la pregunta que queramos responder.

In [11]:
df.loc[:, ["sucursal", "producto", "cantidad_vendida"]]

  sucursal    producto  cantidad_vendida
0   Centro    Cuaderno                15
1   Centro    Lapicera                40
2    Norte     Mochila                 5
3      Sur       Regla                25
4    Norte  Cartuchera                 8
5      Sur    Cuaderno                12
6   Centro  Marcadores                10
7    Norte     Carpeta                18
8      Sur        Goma                30
9   Centro       Lapiz                50

En este caso seleccionamos tres columnas: `sucursal`, `producto` y `cantidad_vendida`. Esta selección podría servir para observar qué productos se vendieron, en qué sucursal y en qué cantidad.

La ventaja de `loc` es que la instrucción deja explícitas las dos dimensiones de la selección:

```python
df.loc[filas, columnas]
```

Cuando escribimos:

```python
df.loc[:, ["sucursal", "producto", "cantidad_vendida"]]
```

estamos diciendo que queremos conservar todas las filas, pero solo algunas columnas. Esta forma es muy clara cuando necesitamos seleccionar filas y columnas al mismo tiempo, como veremos a continuación.

## Seleccionar filas y columnas con loc

La mayor ventaja de `loc` aparece cuando queremos seleccionar filas y columnas al mismo tiempo usando etiquetas.

La estructura general es:

```python
df.loc[filas, columnas]
```

En la parte de filas indicamos qué etiquetas del índice queremos seleccionar. En la parte de columnas indicamos qué nombres de columnas queremos conservar.

Por ejemplo, podemos seleccionar las filas con etiquetas `0`, `1`, `2` y `3`, y quedarnos solamente con las columnas `producto` y `precio`.

In [12]:
df.loc[0:3, ["producto", "precio"]]

   producto  precio
0  Cuaderno    1200
1  Lapicera     350
2   Mochila    8500
3     Regla     500

Esta instrucción puede leerse así: seleccioná las filas desde la etiqueta `0` hasta la etiqueta `3`, y de esas filas mostrá solamente las columnas `producto` y `precio`.

Recordemos que, con `loc`, el final del rango se incluye. Por eso `0:3` incluye las etiquetas `0`, `1`, `2` y `3`.

También podemos seleccionar filas puntuales y columnas puntuales:

In [13]:
df.loc[[0, 4, 8], ["producto", "sucursal", "fecha"]]

     producto sucursal       fecha
0    Cuaderno   Centro  2024-03-01
4  Cartuchera    Norte  2024-03-03
8        Goma      Sur  2024-03-05

En este caso seleccionamos las filas con etiquetas `0`, `4` y `8`, y conservamos las columnas `producto`, `sucursal` y `fecha`.

Esta forma de selección es muy expresiva porque podemos leer con bastante claridad qué parte del dataset estamos pidiendo.

Por ejemplo:

```python
df.loc[[0, 4, 8], ["producto", "sucursal", "fecha"]]
```

puede interpretarse como: “mostrá las ventas identificadas con las etiquetas `0`, `4` y `8`, pero solo con la información de producto, sucursal y fecha”.

A medida que los datasets crecen, esta claridad se vuelve cada vez más importante. Seleccionar por nombres de columnas suele ser más legible que seleccionar por posiciones numéricas, especialmente cuando no recordamos el orden exacto de las columnas.

## Un ejemplo donde índice y posición no coinciden

Hasta ahora, nuestro `DataFrame` tiene un índice automático que va de `0` a `9`. En ese caso, las etiquetas del índice coinciden visualmente con las posiciones de las filas. Pero esto no siempre ocurre.

Para verlo con más claridad, vamos a crear una copia del `DataFrame` y vamos a usar la columna `producto` como índice.

In [14]:
df_productos = df.set_index("producto")

df_productos

             categoria  precio  cantidad_vendida sucursal       fecha
producto
Cuaderno      Libreria    1200                15   Centro  2024-03-01
Lapicera      Libreria     350                40   Centro  2024-03-01
Mochila     Accesorios    8500                 5    Norte  2024-03-02
Regla         Libreria     500                25      Sur  2024-03-02
Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
Cuaderno      Libreria    1250                12      Sur  2024-03-03
Marcadores    Libreria    1800                10   Centro  2024-03-04
Carpeta       Libreria     950                18    Norte  2024-03-04
Goma          Libreria     300                30      Sur  2024-03-05
Lapiz         Libreria     250                50   Centro  2024-03-05

Ahora el índice ya no está formado por los números `0`, `1`, `2`, `3`, etc. El índice está formado por los nombres de los productos.

Esto cambia la forma en que usamos `loc`.

Por ejemplo, ahora podemos seleccionar las filas cuyo índice es `"Cuaderno"`:

In [15]:
df_productos.loc["Cuaderno"]

         categoria  precio  cantidad_vendida sucursal       fecha
producto
Cuaderno  Libreria    1200                15   Centro  2024-03-01
Cuaderno  Libreria    1250                12      Sur  2024-03-03

La salida muestra las filas asociadas al producto `"Cuaderno"`.

En este dataset, `"Cuaderno"` aparece más de una vez, por eso Pandas devuelve más de una fila. En cambio, si usamos `iloc`, seguimos seleccionando por posición:

In [16]:
df_productos.iloc[0]

categoria             Libreria
precio                    1200
cantidad_vendida            15
sucursal                Centro
fecha               2024-03-01
Name: Cuaderno, dtype: object

Esta instrucción no busca el producto `"Cuaderno"` por su etiqueta. Simplemente selecciona la primera fila del `DataFrame`.

La diferencia central sigue siendo la misma:

```text
loc  → selecciona por etiqueta
iloc → selecciona por posición
```

En este nuevo `DataFrame`, la diferencia se vuelve más visible porque las etiquetas del índice ya no son iguales a las posiciones numéricas.

## Etiquetas repetidas en el índice

En el ejemplo anterior usamos `set_index("producto")` para crear un nuevo `DataFrame` llamado `df_productos`. Esto nos permitió usar los nombres de los productos como índice. Sin embargo, apareció una situación interesante: el producto `"Cuaderno"` aparece más de una vez en el dataset.

Eso significa que el índice tiene etiquetas repetidas. Cuando usamos:

In [17]:
df_productos.loc["Cuaderno"]

         categoria  precio  cantidad_vendida sucursal       fecha
producto
Cuaderno  Libreria    1200                15   Centro  2024-03-01
Cuaderno  Libreria    1250                12      Sur  2024-03-03

Pandas devuelve todas las filas cuyo índice tiene la etiqueta `"Cuaderno"`.

Esto es importante porque `loc` no necesariamente devuelve una sola fila. Si la etiqueta buscada aparece una sola vez, puede devolver una fila. Si aparece varias veces, puede devolver varias filas.

Podemos probarlo con un producto que aparece una sola vez:

In [18]:
df_productos.loc["Mochila"]

categoria           Accesorios
precio                    8500
cantidad_vendida             5
sucursal                 Norte
fecha               2024-03-02
Name: Mochila, dtype: object

En este caso, como `"Mochila"` aparece una sola vez, Pandas devuelve una sola fila.

Este ejemplo nos ayuda a entender que el índice no siempre funciona como un identificador único. A veces puede tener valores repetidos. Eso no está necesariamente mal, pero debemos saberlo para interpretar correctamente el resultado de una selección.

Más adelante vamos a volver sobre el índice con más detalle. Por ahora, lo importante es recordar que `loc` busca etiquetas, y si una etiqueta aparece más de una vez, puede devolver más de una fila.

## Errores frecuentes al usar loc

Cuando usamos `loc`, debemos recordar que estamos seleccionando por etiquetas. Esto significa que las filas se seleccionan usando etiquetas del índice y las columnas se seleccionan usando sus nombres.

Un error frecuente es intentar usar posiciones numéricas como si siempre fueran etiquetas. En nuestro primer `DataFrame`, esto parecía funcionar porque el índice estaba formado por números del `0` al `9`. Pero cuando cambiamos el índice y usamos `producto` como etiqueta, la situación cambió.

Por ejemplo, en `df_productos`, el índice está formado por nombres de productos:

In [19]:
df_productos.head()

             categoria  precio  cantidad_vendida sucursal       fecha
producto
Cuaderno      Libreria    1200                15   Centro  2024-03-01
Lapicera      Libreria     350                40   Centro  2024-03-01
Mochila     Accesorios    8500                 5    Norte  2024-03-02
Regla         Libreria     500                25      Sur  2024-03-02
Cartuchera  Accesorios    3200                 8    Norte  2024-03-03

En ese `DataFrame`, esta instrucción no busca la primera fila:

In [20]:
# Esta instrucción produciría un error si no existe una etiqueta de índice llamada 0.
# df_productos.loc[0]

Si queremos seleccionar la primera fila por posición, debemos usar `iloc`:

In [21]:
df_productos.iloc[0]

categoria             Libreria
precio                    1200
cantidad_vendida            15
sucursal                Centro
fecha               2024-03-01
Name: Cuaderno, dtype: object

En cambio, si queremos seleccionar por etiqueta, usamos `loc` con una etiqueta existente del índice:

In [22]:
df_productos.loc["Cuaderno"]

         categoria  precio  cantidad_vendida sucursal       fecha
producto
Cuaderno  Libreria    1200                15   Centro  2024-03-01
Cuaderno  Libreria    1250                12      Sur  2024-03-03

Otro error frecuente es escribir mal el nombre de una columna. Como `loc` selecciona columnas por nombre, esos nombres deben coincidir exactamente con los del `DataFrame`.

Por ejemplo:

In [23]:
# Esta instrucción produciría un error porque la columna se llama "precio", no "Precio".
# df.loc[:, "Precio"]

Para evitar este tipo de problemas, conviene revisar los nombres disponibles antes de seleccionar:

In [24]:
df.columns

Index(['producto', 'categoria', 'precio', 'cantidad_vendida', 'sucursal',
       'fecha'],
      dtype='object')

La regla general es sencilla: si usamos `iloc`, pensamos en posiciones; si usamos `loc`, pensamos en etiquetas. Esa diferencia ayuda a decidir qué herramienta corresponde en cada situación.

## Resumen del capítulo

En este capítulo aprendimos a seleccionar datos usando `loc`.

A diferencia de `iloc`, que trabaja con posiciones numéricas, `loc` trabaja con etiquetas. Esto significa que podemos seleccionar filas usando etiquetas del índice y columnas usando sus nombres.

Primero comparamos estas dos herramientas:

```text
iloc selecciona por posición.
loc selecciona por etiqueta.
```

En nuestro `DataFrame` original, el índice estaba formado por números del `0` al `9`, por eso al comienzo parecía que `iloc` y `loc` se comportaban de manera muy parecida. Sin embargo, la diferencia conceptual es importante: `df.iloc[0]` selecciona la primera fila por posición, mientras que `df.loc[0]` selecciona la fila cuya etiqueta de índice es `0`.

También vimos que `loc` permite seleccionar varias filas usando listas de etiquetas o rangos. En ese punto apareció una diferencia clave con `iloc`: cuando usamos rangos con `loc`, el valor final del rango se incluye.

Por ejemplo:

```python
df.loc[0:3]
```

selecciona las etiquetas `0`, `1`, `2` y `3`.

Después usamos `loc` para seleccionar columnas por nombre. Para eso trabajamos con la estructura:

```python
df.loc[filas, columnas]
```

Cuando queremos conservar todas las filas y seleccionar una columna, podemos escribir:

```python
df.loc[:, "precio"]
```

Y cuando queremos seleccionar varias columnas:

```python
df.loc[:, ["producto", "precio"]]
```

Más adelante combinamos filas y columnas en una misma selección:

```python
df.loc[0:3, ["producto", "precio"]]
```

Esta forma de trabajo es muy legible porque permite expresar directamente qué filas y qué columnas queremos observar.

También creamos un nuevo `DataFrame` usando `set_index("producto")` para mostrar un caso en el que índice y posición ya no coinciden. Ese ejemplo nos permitió ver con más claridad que `loc` busca etiquetas, mientras que `iloc` busca posiciones.

Una idea importante fue que el índice puede tener etiquetas repetidas. Cuando usamos `loc` con una etiqueta repetida, Pandas devuelve todas las filas que tienen esa etiqueta.

La idea principal de este capítulo fue:

```text
loc permite seleccionar datos usando etiquetas del índice y nombres de columnas.
```

Esta herramienta será muy útil para construir selecciones más claras y expresivas, especialmente cuando trabajemos con datasets más grandes o con índices personalizados.

## Próximo paso

Ya sabemos seleccionar columnas, seleccionar filas por posición con `iloc` y seleccionar datos por etiquetas con `loc`.

El siguiente paso será aprender a filtrar filas usando condiciones. Esto nos permitirá responder preguntas más específicas, como seleccionar solo las ventas de una sucursal, solo los productos de una categoría o solo los registros que superen cierto precio.

A partir de ahí, las selecciones dejarán de depender solamente de posiciones o etiquetas, y empezarán a depender del contenido real de los datos.